// ============================================================
// הקטלוג המורחב — 49 מוצרי הדגמה נוספים (x1–x49)
// ⚠️ תוכן המחשה עד קבלת סחורה אמיתית. עריכה: אובייקט אחד למוצר.
// התמונות: public/images/products (מיוצרות ע"י scripts/generate-product-images.mjs)
// ============================================================

import type { CatalogProduct } from '@/lib/catalog';
import {
  KIPPAH_CUSTOMIZATION,
  TALLIT_CUSTOMIZATION,
  ENGRAVING_SILVER,
  EMBOSS_LEATHER,
  PRINT_PERSONAL,
} from '@/lib/customization-presets';

const IMG = '/images/products';

type ProductInput = Omit<CatalogProduct, 'gallery' | 'isPlaceholderImage'> &
  Partial<Pick<CatalogProduct, 'gallery' | 'isPlaceholderImage'>>;

// ברירות מחדל אחידות — גלריה מהתמונה הראשית + סימון "תמונת המחשה"
function def(data: ProductInput): CatalogProduct {
  const src = data.imageUrl!;
  return {
    isPlaceholderImage: true,
    gallery: [
      { src, label: 'מבט ראשי' },
      { src, label: 'תקריב', zoom: 1.7 },
      { src, label: 'פרט עיצוב', zoom: 2.4 },
    ],
    ...data,
  };
}

export const EXTENDED_PRODUCTS: CatalogProduct[] = [
  // ================= כיפות =================
  def({
    id: 'x1', sku: 'EB-KP-101', slug: 'kippah-velvet-black-classic',
    titleHe: 'כיפת קטיפה שחורה קלאסית', imageUrl: `${IMG}/kippah-velvet-black.svg`,
    category: 'כיפות', subcategory: 'כיפות קטיפה',
    material: 'קטיפה איכותית, 4 חלקים', basePrice: 35, isCustomizable: true, iconKey: 'kippah',
    shortDescription: 'כיפת הקטיפה הקלאסית — תפירה חזקה, בטנה מלאה וישיבה יציבה על הראש.',
    longDescription: ['כיפת קטיפה שחורה בתפירת 4 חלקים עם בטנת סאטן. הקטיפה עמידה לשימוש יומיומי ושומרת על גוון עמוק גם אחרי זמן. ניתן להוסיף רקמת שם בפנים או בשוליים.'],
    materials: ['קטיפה', 'בטנת סאטן'], dimensions: 'מידות 2–6 (קוטר 15–22 ס"מ)',
    prepTimeDays: [1, 3], tags: ['קטיפה', 'יומיומי', 'רקמה אישית'],
    relatedSlugs: ['knitted-kippah-custom', 'kippah-satin-white-event', 'tallit-bag-velvet-embroidery'],
    stockStatus: 'in-stock', badges: ['bestseller'], audience: ['men', 'kids'],
    variantGroups: [{ id: 'size', label: 'מידה', options: [
      { id: '2', label: 'מידה 2 (ילדים)', priceDelta: -5 }, { id: '4', label: 'מידה 4', priceDelta: 0 }, { id: '6', label: 'מידה 6 (גדול)', priceDelta: 5 },
    ]}],
    customization: { ...KIPPAH_CUSTOMIZATION, surcharges: { text: 12, symbol: 8, logo: 20, giftWrap: 12 } },
  }),
  def({
    id: 'x2', sku: 'EB-KP-102', slug: 'kippah-satin-white-event',
    titleHe: 'כיפת סאטן לבנה לאירועים', imageUrl: `${IMG}/kippah-satin-white.svg`,
    category: 'כיפות', subcategory: 'כיפות לאירועים',
    material: 'סאטן מבריק, תפירה עדינה', basePrice: 22, isCustomizable: true, iconKey: 'kippah',
    shortDescription: 'הבחירה הקלאסית לחתונות ובר מצוות — קלה, מבריקה ונוחה, עם הדפסה או רקמה לאירוע.',
    longDescription: ['כיפת סאטן לבנה בתפירת 4 חלקים — הסטנדרט באירועים ישראליים. בהזמנת כמות לאירוע ניתן להוסיף רקמת שם החתן/חתן הבר מצווה ותאריך, עם הנחת כמות מדורגת.'],
    materials: ['סאטן'], dimensions: 'מידה אחידה (קוטר 19 ס"מ)',
    prepTimeDays: [2, 5], tags: ['אירועים', 'חתונה', 'בר מצווה', 'הזמנה בכמות'],
    relatedSlugs: ['kippot-event-branded', 'wedding-breaking-glass-set', 'kippah-velvet-black-classic'],
    stockStatus: 'in-stock', badges: [], audience: ['men'], occasions: ['חתונה', 'בר מצווה'],
    customization: { ...KIPPAH_CUSTOMIZATION, surcharges: { text: 8, symbol: 6, logo: 15, giftWrap: 10 } },
  }),
  def({
    id: 'x3', sku: 'EB-KP-103', slug: 'kippah-suede-navy',
    titleHe: 'כיפת זמש נייבי — גזרה צרה', imageUrl: `${IMG}/kippah-suede-navy.svg`,
    category: 'כיפות', subcategory: 'כיפות עור וזמש',
    material: 'זמש רך, 6 חלקים', basePrice: 69, isCustomizable: false, iconKey: 'kippah',
    shortDescription: 'זמש איכותי בגזרת 6 חלקים צרה — מראה נקי ומודרני שמחזיק צורה.',
    longDescription: ['כיפת זמש כחול-לילה בתפירת 6 חלקים. הזמש נעים למגע, לא מחליק, ומתאים גם לשימוש יומיומי וגם לאירועים. שוליים תפורים כפול לעמידות.'],
    materials: ['זמש'], dimensions: 'קוטר 17 ס"מ',
    prepTimeDays: [1, 3], tags: ['זמש', 'מודרני'],
    relatedSlugs: ['kippah-leather-handmade', 'kippah-velvet-black-classic', 'knitted-kippah-custom'],
    stockStatus: 'in-stock', badges: [], audience: ['men'],
  }),
  def({
    id: 'x4', sku: 'EB-KP-104', slug: 'kippah-leather-handmade',
    titleHe: 'כיפת עור אמיתי בעבודת יד', imageUrl: `${IMG}/kippah-leather-brown.svg`,
    category: 'כיפות', subcategory: 'כיפות עור וזמש',
    material: 'עור איטלקי, תפירה ידנית', basePrice: 149, isCustomizable: true, iconKey: 'kippah',
    shortDescription: 'עור איטלקי בגוון קוניאק, נתפר ביד — עם אפשרות הטבעת שם או ראשי תיבות.',
    longDescription: ['כיפת עור אמיתי בעבודת יד: כל כיפה נחתכת ונתפרת ידנית מעור איטלקי רך שמתיישן יפה עם השנים. ניתן להטביע שם, ראשי תיבות או תאריך בפויל זהב — מתנה אישית ומוקפדת.'],
    materials: ['עור איטלקי אמיתי'], dimensions: 'קוטר 17 ס"מ',
    prepTimeDays: [4, 8], tags: ['עור', 'עבודת יד', 'הטבעה אישית', 'מתנה לגבר'],
    relatedSlugs: ['kippah-suede-navy', 'siddur-leather-custom-emboss', 'necklace-magen-david-men'],
    stockStatus: 'made-to-order', badges: ['handmade', 'luxury'], audience: ['men'],
    customization: EMBOSS_LEATHER,
  }),
  def({
    id: 'x5', sku: 'EB-KP-105', slug: 'kippah-kids-colorful',
    titleHe: 'כיפה סרוגה צבעונית לילדים', imageUrl: `${IMG}/kippah-kids-colorful.svg`,
    category: 'כיפות', subcategory: 'כיפות לילדים',
    material: 'סריגה צפופה, כותנה', basePrice: 29, isCustomizable: true, iconKey: 'kippah',
    shortDescription: 'כיפה סרוגה עליזה לילדים עם דוגמת מעוינים — ואפשרות לרקום את השם.',
    longDescription: ['כיפה סרוגה לילדים בטורקיז עם דוגמת מעוינים לבנה ושוליים זהובים. סריגה צפופה שלא מתקפלת, וקוטר מותאם לגילאי 3–10. רקמת שם הילד הופכת אותה לאהובה במיוחד.'],
    materials: ['חוט כותנה'], dimensions: 'קוטר 15 ס"מ',
    prepTimeDays: [3, 7], tags: ['ילדים', 'רקמה אישית', 'צבעוני'],
    relatedSlugs: ['tallit-kids-first', 'necklace-kids-hamsa', 'mezuzah-ceramic-kids'],
    stockStatus: 'in-stock', badges: ['new'], audience: ['kids'],
    customization: { ...KIPPAH_CUSTOMIZATION, maxChars: 12, surcharges: { text: 10, symbol: 8, logo: 0, giftWrap: 10 } },
  }),
  def({
    id: 'x6', sku: 'EB-KP-106', slug: 'kippah-breslev-white-large',
    titleHe: 'כיפה סרוגה גדולה לבנה', imageUrl: `${IMG}/kippah-breslev-white.svg`,
    category: 'כיפות', subcategory: 'כיפות סרוגות',
    material: 'סריגת יד, כותנה עבה', basePrice: 59, isCustomizable: true, iconKey: 'kippah',
    shortDescription: 'כיפה סרוגה גדולה ולבנה בסריגה עבה — נוחה, מאווררת ומכסה יפה.',
    longDescription: ['כיפה סרוגה לבנה בקוטר גדול (24 ס"מ) בסריגת חוט עבה. יושבת יציב בלי סיכות, מתאימה לשבת ולכל יום. ניתן להוסיף שורת טקסט ארוגה בשוליים.'],
    materials: ['חוט כותנה עבה'], dimensions: 'קוטר 24 ס"מ',
    prepTimeDays: [2, 6], tags: ['סרוגה', 'גדולה', 'לבן'],
    relatedSlugs: ['knitted-kippah-custom', 'kippah-kids-colorful', 'tzitzit-katan-cotton'],
    stockStatus: 'in-stock', badges: [], audience: ['men'],
    customization: KIPPAH_CUSTOMIZATION,
  }),
  def({
    id: 'x7', sku: 'EB-KP-107', slug: 'kippot-event-branded',
    titleHe: 'כיפות ממותגות לאירועים ומוסדות', imageUrl: `${IMG}/kippot-event-branded.svg`,
    category: 'כיפות', subcategory: 'כיפות לאירועים',
    material: 'קטיפה / סאטן / סרוגה — לבחירה', basePrice: 18, isCustomizable: true, iconKey: 'kippah',
    shortDescription: 'כיפות בכמות עם מיתוג מלא לאירוע או למוסד — צבע, טקסט ולוגו לבחירתכם.',
    longDescription: ['פתרון מלא לאירועים ומוסדות: בוחרים סוג כיפה (קטיפה, סאטן או סרוגה), צבע, טקסט פנימי או חיצוני ולוגו — ואנחנו מייצרים בכמות עם אחידות מלאה. המחיר ליחידה יורד ככל שהכמות עולה; לקבלת הצעה מדויקת השאירו פרטים.'],
    materials: ['לבחירה לפי סוג הכיפה'], prepTimeDays: [10, 21],
    tags: ['אירועים', 'מוסדות', 'לוגו', 'הזמנה בכמות', 'חתונה', 'בר מצווה'],
    relatedSlugs: ['kippah-satin-white-event', 'corporate-gifts-branded', 'wedding-breaking-glass-set'],
    stockStatus: 'made-to-order', badges: [], priceType: 'quote',
    occasions: ['חתונה', 'בר מצווה'], audience: ['men', 'family'],
  }),

  // ================= טליתות וציציות =================
  def({
    id: 'x8', sku: 'EB-TL-101', slug: 'tallit-acrylic-barmitzvah',
    titleHe: 'טלית אקרילן לבר מצווה — פסים כחולים', imageUrl: `${IMG}/tallit-acrylic-blue.svg`,
    category: 'ציציות וטליתות', subcategory: 'טליתות אקרילן',
    material: 'אקרילן קל, ציציות קשורות', basePrice: 280, isCustomizable: true, iconKey: 'tallit',
    shortDescription: 'טלית קלה ונעימה לנער — פסים כחול-זהב, מחיר נגיש ורקמת שם לבר המצווה.',
    longDescription: ['טלית אקרילן איכותית לבר מצווה: קלה על הכתפיים, לא מגרדת, עם פסים כחולים ופס זהב עדין. הציציות מגיעות קשורות. רקמת שם הנער ותאריך בר המצווה על העטרה הופכת אותה לזיכרון לכל החיים.'],
    materials: ['אקרילן', 'עטרה ארוגה'], dimensions: 'מידה 50 (מתאימה לנער)',
    prepTimeDays: [4, 9], tags: ['בר מצווה', 'אקרילן', 'רקמה אישית'],
    relatedSlugs: ['barmitzvah-complete-set', 'tallit-bag-velvet-embroidery', 'tallit-beit-yosef-sefard'],
    stockStatus: 'in-stock', badges: ['bestseller'], audience: ['kids', 'men'], occasions: ['בר מצווה'],
    customization: TALLIT_CUSTOMIZATION,
  }),
  def({
    id: 'x9', sku: 'EB-TL-102', slug: 'tallit-kids-first',
    titleHe: 'טלית ראשונה לילד — צבעי חג', imageUrl: `${IMG}/tallit-kids.svg`,
    category: 'ציציות וטליתות', subcategory: 'טליתות לילדים',
    material: 'אקרילן רך, עטרה מוזהבת', basePrice: 180, isCustomizable: true, iconKey: 'tallit',
    shortDescription: 'טלית קטנה וקלה לילדים עם פסי טורקיז וירוק — חוויה ראשונה שמחה של מצווה.',
    longDescription: ['טלית ראשונה בגודל מותאם לילדים, מבד רך שלא מכביד, עם פסים צבעוניים ועטרה מוזהבת. מתנה מרגשת לגן, לעלייה לתורה ראשונה או "לחיקוי אבא" בבית הכנסת.'],
    materials: ['אקרילן רך'], dimensions: 'מידה 30',
    prepTimeDays: [3, 7], tags: ['ילדים', 'טלית ראשונה', 'מתנה'],
    relatedSlugs: ['kippah-kids-colorful', 'tallit-acrylic-barmitzvah', 'necklace-kids-hamsa'],
    stockStatus: 'in-stock', badges: ['new'], audience: ['kids'],
    customization: { ...TALLIT_CUSTOMIZATION, maxChars: 14, surcharges: { text: 40, symbol: 20, logo: 0, giftWrap: 25 } },
  }),
  def({
    id: 'x10', sku: 'EB-TL-103', slug: 'tallit-premium-light-wool',
    titleHe: 'טלית צמר קלה "הרים" — פרימיום', imageUrl: `${IMG}/tallit-premium-light.svg`,
    category: 'ציציות וטליתות', subcategory: 'טליתות צמר',
    material: 'צמר קל במיוחד, פסי זהב ארוגים', basePrice: 1650, isCustomizable: true, iconKey: 'tallit',
    shortDescription: 'קולקציית הפרימיום: צמר קל במיוחד עם פסי זהב ארוגים ועטרה בעבודת יד.',
    longDescription: ['טלית "הרים" נטווית מסיבי צמר דקים במיוחד — קלה כמעט כמו אקרילן אך עם הנפילה והחום של צמר אמיתי. פסי הזהב ארוגים לתוך הבד (לא מודפסים), והעטרה נרקמת ביד. מיוצרת בהזמנה, לחתנים ולמי שמחפש את הטלית של החיים.'],
    materials: ['צמר משובח קל', 'עטרה רקומה ביד'], dimensions: 'מידות 60 / 70 / 80',
    prepTimeDays: [10, 18], tags: ['פרימיום', 'צמר', 'עבודת יד', 'חתן'],
    relatedSlugs: ['tallit-beit-yosef-sefard', 'atara-silver-woven', 'tallit-bag-velvet-embroidery'],
    stockStatus: 'made-to-order', badges: ['luxury', 'handmade'], audience: ['men'], occasions: ['חתונה'],
    variantGroups: [{ id: 'size', label: 'מידה', options: [
      { id: '60', label: 'מידה 60', priceDelta: 0 }, { id: '70', label: 'מידה 70', priceDelta: 150 }, { id: '80', label: 'מידה 80', priceDelta: 300 },
    ]}],
    customization: TALLIT_CUSTOMIZATION,
  }),
  def({
    id: 'x11', sku: 'EB-TL-104', slug: 'tzitzit-katan-cotton',
    titleHe: 'טלית קטן כותנה — ציציות קשורות', imageUrl: `${IMG}/tzitzit-katan.svg`,
    category: 'ציציות וטליתות', subcategory: 'ציציות ואביזרים',
    material: 'כותנה 100%, ציציות צמר', basePrice: 45, isCustomizable: false, iconKey: 'tallit',
    shortDescription: 'טלית קטן מכותנה נושמת עם ציציות צמר קשורות — נוח לכל היום.',
    longDescription: ['טלית קטן מכותנה רכה ונושמת, בגזרה נוחה שלא מתקפלת. הציציות עשויות צמר לשמה ומגיעות קשורות. זמין בקשירת אשכנז וספרד ובמגוון מידות לילדים ולמבוגרים.'],
    materials: ['כותנה 100%', 'ציציות צמר לשמה'], dimensions: 'מידות 14–24',
    prepTimeDays: [1, 3], tags: ['ציצית', 'יומיומי', 'כותנה'],
    relatedSlugs: ['tallit-beit-yosef-sefard', 'kippah-breslev-white-large', 'tallit-kids-first'],
    stockStatus: 'in-stock', badges: [], audience: ['men', 'kids'],
    variantGroups: [
      { id: 'size', label: 'מידה', options: [
        { id: '16', label: '16 (ילדים)', priceDelta: -10 }, { id: '20', label: '20', priceDelta: 0 }, { id: '24', label: '24 (גדול)', priceDelta: 8 },
      ]},
      { id: 'knot', label: 'קשירה', options: [
        { id: 'ashkenaz', label: 'אשכנז', priceDelta: 0 }, { id: 'sefard', label: 'ספרד', priceDelta: 0 },
      ]},
    ],
  }),
  def({
    id: 'x12', sku: 'EB-TL-105', slug: 'atara-silver-woven',
    titleHe: 'עטרה ארוגה בחוט כסף לטלית', imageUrl: `${IMG}/atara-silver.svg`,
    category: 'ציציות וטליתות', subcategory: 'ציציות ואביזרים',
    material: 'אריגת חוט כסף על בסיס בד', basePrice: 320, isCustomizable: false, iconKey: 'tallit',
    shortDescription: 'שדרוג מפואר לטלית קיימת: עטרה ארוגה בחוט כסף בדוגמת גלים קלאסית.',
    longDescription: ['עטרה ארוגה בחוט מטאלי כסוף על בסיס בד חזק, בדוגמת גלים מסורתית. מתאימה להחלפה או שדרוג של עטרה בטלית קיימת — שירות התפירה כלול במחיר.'],
    materials: ['חוט כסף מטאלי', 'בסיס בד'], dimensions: 'אורך 90 ס"מ · רוחב 12 ס"מ',
    prepTimeDays: [5, 10], tags: ['עטרה', 'שדרוג', 'כסף'],
    relatedSlugs: ['tallit-premium-light-wool', 'tallit-beit-yosef-sefard', 'tallit-bag-velvet-embroidery'],
    stockStatus: 'made-to-order', badges: ['handmade'],
  }),

  // ================= מטפחות =================
  def({
    id: 'x13', sku: 'EB-HS-101', slug: 'scarf-cotton-daily',
    titleHe: 'מטפחת כותנה יומיומית — תכלת אבן', imageUrl: `${IMG}/scarf-cotton.svg`,
    category: 'מטפחות מעוצבות', subcategory: 'כותנה יומיומית',
    material: 'כותנה נושמת', basePrice: 85, isCustomizable: false, iconKey: 'textile',
    shortDescription: 'מטפחת הכותנה שנוח איתה כל היום — נושמת, לא מחליקה ומתאימה לכל קשירה.',
    longDescription: ['מטפחת כותנה בגוון תכלת-אבן רגוע. הבד נושם ונעים גם בקיץ הישראלי, אחיזתו טובה ואינו דורש סיכות. מידה נדיבה שמאפשרת מגוון קשירות.'],
    materials: ['כותנה 100%'], dimensions: '100×100 ס"מ',
    prepTimeDays: [1, 3], tags: ['יומיומי', 'כותנה', 'נוח'],
    relatedSlugs: ['silk-headscarf-designed', 'scarf-satin-evening', 'scarf-duo-giftbox'],
    stockStatus: 'in-stock', badges: ['bestseller'], audience: ['women'],
  }),
  def({
    id: 'x14', sku: 'EB-HS-102', slug: 'scarf-satin-evening',
    titleHe: 'מטפחת סאטן לערב — ורוד עתיק', imageUrl: `${IMG}/scarf-satin-blush.svg`,
    category: 'מטפחות מעוצבות', subcategory: 'מטפחות ערב',
    material: 'סאטן כבד עם ברק עדין', basePrice: 160, isCustomizable: false, iconKey: 'textile',
    shortDescription: 'ברק עדין לאירועים: סאטן כבד בוורוד עתיק עם שוליים בגימור זהב.',
    longDescription: ['מטפחת ערב מסאטן כבד ואיכותי שנופל יפה ומחזיק נפח. הגוון — ורוד עתיק מחמיא — עם שוליים בתפירת זהב. משלימה מושלמת לשמלת ערב ולשמחות.'],
    materials: ['סאטן'], dimensions: '105×105 ס"מ',
    prepTimeDays: [1, 3], tags: ['ערב', 'אירועים', 'סאטן'],
    relatedSlugs: ['silk-headscarf-designed', 'scarf-cotton-daily', 'candlesticks-modern-silver'],
    stockStatus: 'in-stock', badges: [], audience: ['women'], occasions: ['חתונה'],
  }),
  def({
    id: 'x15', sku: 'EB-HS-103', slug: 'scarf-silk-handpainted',
    titleHe: 'מטפחת משי בציור יד — "סגול ירושלים"', imageUrl: `${IMG}/scarf-handpainted.svg`,
    category: 'מטפחות מעוצבות', subcategory: 'מטפחות משי',
    material: 'משי טבעי, צביעה ידנית', basePrice: 420, isCustomizable: false, iconKey: 'textile',
    shortDescription: 'יצירת אמנות לבישה: משי טבעי הנצבע ביד בגווני סגול — כל מטפחת ייחודית.',
    longDescription: ['כל מטפחת בסדרה נצבעת ביד על משי טבעי בטכניקת אקוורל, כך שאין שתי מטפחות זהות. גווני הסגול-לילך מתערבבים בעדינות עם שולי זהב. מגיעה במארז מתנה עם תעודת "עבודת יד".'],
    materials: ['משי טבעי 100%', 'צבעי משי מקצועיים'], dimensions: '110×110 ס"מ',
    prepTimeDays: [7, 14], tags: ['עבודת יד', 'משי', 'מהדורה מוגבלת', 'מתנה לאישה'],
    relatedSlugs: ['silk-headscarf-designed', 'scarf-duo-giftbox', 'necklace-magen-david-silver'],
    stockStatus: 'made-to-order', badges: ['handmade', 'limited'], audience: ['women'],
  }),
  def({
    id: 'x16', sku: 'EB-HS-104', slug: 'scarf-duo-giftbox',
    titleHe: 'מארז מתנה — זוג מטפחות נבחרות', imageUrl: `${IMG}/scarf-giftbox.svg`,
    category: 'מטפחות מעוצבות', subcategory: 'מארזי מתנה',
    material: 'כותנה + סאטן במארז', basePrice: 240, discountPrice: 199, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'מתנה מוכנה: מטפחת כותנה יומיומית + מטפחת סאטן חגיגית בקופסה מעוצבת.',
    longDescription: ['מארז מתנה מוכן לנתינה: מטפחת כותנה לכל יום ומטפחת סאטן לשבת ולאירועים, ארוזות בקופסה מעוצבת עם סרט. מתנה מנצחת לכלה, ליולדת או לאירוח.'],
    materials: ['כותנה', 'סאטן', 'קופסת מתנה'], prepTimeDays: [1, 3],
    tags: ['מארז', 'מתנה לאישה', 'כלה', 'יולדת'],
    relatedSlugs: ['scarf-cotton-daily', 'scarf-satin-evening', 'gift-baby-mazal'],
    stockStatus: 'in-stock', badges: ['recommended'], audience: ['women'], occasions: ['חתונה', 'יולדת'],
  }),

  // ================= קידוש והבדלה =================
  def({
    id: 'x17', sku: 'EB-KC-101', slug: 'kiddush-hammered-steel',
    titleHe: 'גביע קידוש מרוקע — נירוסטה בציפוי כסף', imageUrl: `${IMG}/kiddush-hammered.svg`,
    category: 'כוסות קידוש', subcategory: 'גביעי קידוש',
    material: 'נירוסטה בציפוי כסף, ריקוע יד', basePrice: 180, isCustomizable: true, iconKey: 'kiddush',
    shortDescription: 'מראה של כסף מרוקע במחיר נגיש — עמיד, לא משחיר וניתן לחריטה.',
    longDescription: ['גביע בעיצוב מרוקע קלאסי, מנירוסטה בציפוי כסף עמיד שאינו דורש הברקה. פתרון מצוין למי שרוצה את המראה המסורתי בלי התחזוקה. ניתן להוסיף חריטת שם.'],
    materials: ['נירוסטה', 'ציפוי כסף'], dimensions: 'גובה 13 ס"מ · 120 מ"ל',
    prepTimeDays: [2, 5], tags: ['נגיש', 'עמיד', 'חריטה אישית'],
    relatedSlugs: ['kiddush-cup-jerusalem-925', 'kiddush-set-six-cups', 'kiddush-kids-cup'],
    stockStatus: 'in-stock', badges: ['bestseller'],
    customization: { ...ENGRAVING_SILVER, surcharges: { text: 50, symbol: 25, logo: 0, giftWrap: 25 } },
  }),
  def({
    id: 'x18', sku: 'EB-KC-102', slug: 'kiddush-set-six-cups',
    titleHe: 'סט קידוש משפחתי — גביע, 6 כוסיות ומגש', imageUrl: `${IMG}/kiddush-set-cups.svg`,
    category: 'כוסות קידוש', subcategory: 'סטים לשולחן',
    material: 'ציפוי כסף על מגש תואם', basePrice: 890, discountPrice: 790, isCustomizable: true, iconKey: 'kiddush',
    shortDescription: 'כל השולחן מסודר: גביע מרכזי, שש כוסיות תואמות ומגש — סט שגדל עם המשפחה.',
    longDescription: ['סט קידוש שלם למשפחה: גביע מרכזי מהודר, שש כוסיות קטנות לבני הבית ומגש תואם. הציפוי עמיד ומיועד לשימוש שבועי. אפשרות לחריטת שם משפחה על המגש.'],
    materials: ['ציפוי כסף', 'מגש תואם'], dimensions: 'מגש קוטר 30 ס"מ',
    prepTimeDays: [3, 7], tags: ['סט משפחתי', 'שבת', 'חריטה אישית', 'מתנה לחתונה'],
    relatedSlugs: ['kiddush-cup-jerusalem-925', 'challah-set-silver-board', 'havdalah-set-silver'],
    stockStatus: 'in-stock', badges: ['recommended'], audience: ['family'], occasions: ['חתונה', 'בית חדש'],
    customization: { ...ENGRAVING_SILVER, positions: [{ id: 'base', label: 'על המגש' }] },
  }),
  def({
    id: 'x19', sku: 'EB-KC-103', slug: 'eliyahu-cup-gilded',
    titleHe: 'כוס אליהו מוזהבת לליל הסדר', imageUrl: `${IMG}/eliyahu-cup.svg`,
    category: 'כוסות קידוש', subcategory: 'גביעי קידוש',
    material: 'ציפוי זהב על פליז', basePrice: 520, isCustomizable: true, iconKey: 'kiddush',
    shortDescription: 'הכוס שעומדת במרכז השולחן בליל הסדר — גימור זהב מלא ונוכחות מלכותית.',
    longDescription: ['כוס אליהו בגימור זהב מלא, בצורת טוליפ קלאסית עם רגל מדורגת. פריט מרכזי לליל הסדר שמשמש גם ככוס קידוש חגיגית בשאר השנה. ניתן לחרוט הקדשה על הבסיס.'],
    materials: ['פליז בציפוי זהב'], dimensions: 'גובה 15 ס"מ · 140 מ"ל',
    prepTimeDays: [3, 7], tags: ['פסח', 'ליל הסדר', 'זהב', 'חריטה אישית'],
    relatedSlugs: ['seder-plate-silver-six', 'kiddush-cup-jerusalem-925', 'wine-fountain-eight'],
    stockStatus: 'in-stock', badges: ['luxury'], occasions: ['חג'],
    customization: ENGRAVING_SILVER,
  }),
  def({
    id: 'x20', sku: 'EB-KC-104', slug: 'kiddush-kids-cup',
    titleHe: 'גביע קידוש לילד — עם חריטת שם', imageUrl: `${IMG}/kiddush-kids.svg`,
    category: 'כוסות קידוש', subcategory: 'לילדים',
    material: 'ציפוי כסף, גודל מוקטן', basePrice: 140, isCustomizable: true, iconKey: 'kiddush',
    shortDescription: '"הגביע שלי!" — גביע מוקטן לילדים עם חריטת שם, לחוויית קידוש משלהם.',
    longDescription: ['גביע קידוש בגודל מותאם ליד קטנה, מציפוי כסף עמיד. חריטת שם הילד כלולה במחיר — מתנה קלאסית לברית, ליום הולדת ולסדר פסח ראשון.'],
    materials: ['ציפוי כסף'], dimensions: 'גובה 9 ס"מ · 60 מ"ל',
    prepTimeDays: [3, 6], tags: ['ילדים', 'חריטה כלולה', 'ברית', 'מתנה'],
    relatedSlugs: ['kiddush-hammered-steel', 'necklace-kids-hamsa', 'candlestick-girl-first'],
    stockStatus: 'in-stock', badges: ['new'], audience: ['kids'], occasions: ['יולדת'],
    customization: { ...ENGRAVING_SILVER, maxChars: 12, surcharges: { text: 0, symbol: 20, logo: 0, giftWrap: 20 } },
  }),
  def({
    id: 'x21', sku: 'EB-KC-105', slug: 'wine-fountain-eight',
    titleHe: 'מזרקת יין ל-8 משתתפים', imageUrl: `${IMG}/wine-fountain.svg`,
    category: 'כוסות קידוש', subcategory: 'מזרקות יין',
    material: 'ציפוי כסף, 8 מוצאים', basePrice: 640, isCustomizable: false, iconKey: 'kiddush',
    shortDescription: 'מוזגים פעם אחת — וכל השולחן מקבל: מזרקת יין מרהיבה לשמונה כוסיות.',
    longDescription: ['מזרקת יין קלאסית: מוזגים לגביע העליון והיין זורם בשמונה זרועות לכוסיות התואמות. אפקט מרהיב לשולחן שבת וחג שהילדים מחכים לו. כוללת מגש איסוף.'],
    materials: ['ציפוי כסף'], dimensions: 'גובה 32 ס"מ · מגש 32 ס"מ',
    prepTimeDays: [4, 8], tags: ['שולחן שבת', 'וואו', 'מתנה לחתונה'],
    relatedSlugs: ['kiddush-set-six-cups', 'kiddush-cup-jerusalem-925', 'challah-set-silver-board'],
    stockStatus: 'in-stock', badges: ['recommended'], audience: ['family'], occasions: ['חתונה'],
  }),

  // ================= פמוטים =================
  def({
    id: 'x22', sku: 'EB-CS-101', slug: 'candlesticks-crystal-or',
    titleHe: 'פמוטי קריסטל "אור" — זוג', imageUrl: `${IMG}/candlesticks-crystal.svg`,
    category: 'פמוטים', subcategory: 'קריסטל וזכוכית',
    material: 'קריסטל מלוטש', basePrice: 290, isCustomizable: false, iconKey: 'candles',
    shortDescription: 'אור הנרות מוכפל בקריסטל: זוג פמוטים מלוטשים שמנצנצים בשולחן.',
    longDescription: ['זוג פמוטי קריסטל בליטוש יהלום שמפזר את אור הנרות לכל החדר. הבסיס הכבד מעניק יציבות מלאה, והמראה — קליל וזוהר. מתנה קלאסית לכלה ולעולים לבית חדש.'],
    materials: ['קריסטל'], dimensions: 'גובה 22 ס"מ',
    prepTimeDays: [2, 5], tags: ['קריסטל', 'מתנה לכלה', 'שבת'],
    relatedSlugs: ['candlesticks-modern-silver', 'candle-tray-tempered', 'gift-set-new-home'],
    stockStatus: 'in-stock', badges: ['bestseller'], audience: ['women', 'family'], occasions: ['חתונה', 'בית חדש'],
  }),
  def({
    id: 'x23', sku: 'EB-CS-102', slug: 'candlesticks-travel-folding',
    titleHe: 'פמוטי נסיעות מתקפלים במארז', imageUrl: `${IMG}/candlesticks-travel.svg`,
    category: 'פמוטים', subcategory: 'פמוטי נסיעות',
    material: 'ציפוי כסף, מארז שטוח', basePrice: 120, isCustomizable: true, iconKey: 'candles',
    shortDescription: 'שבת בכל מקום: זוג פמוטים מתקפלים שנכנסים למארז דק בגודל ארנק.',
    longDescription: ['פמוטי נסיעות חכמים: מתקפלים לתוך מארז שטוח שנכנס לכל תיק, ונפתחים לזוג פמוטים יציבים. מלווים נסיעות עבודה, טיולים ואשפוזים — השבת מגיעה איתך. ניתן לחרוט שם על המארז.'],
    materials: ['ציפוי כסף'], dimensions: 'מארז 12×6 ס"מ',
    prepTimeDays: [2, 5], tags: ['נסיעות', 'קומפקטי', 'חריטה אישית'],
    relatedSlugs: ['candlesticks-crystal-or', 'candlesticks-modern-silver', 'gift-hostess-shabbat'],
    stockStatus: 'in-stock', badges: ['new'], audience: ['women'],
    customization: { ...ENGRAVING_SILVER, maxChars: 15, surcharges: { text: 40, symbol: 0, logo: 0, giftWrap: 18 } },
  }),
  def({
    id: 'x24', sku: 'EB-CS-103', slug: 'candlestick-girl-first',
    titleHe: 'פמוט ראשון לילדה — ורוד פנינה', imageUrl: `${IMG}/candlestick-girl.svg`,
    category: 'פמוטים', subcategory: 'לילדות',
    material: 'מתכת בגימור פנינה', basePrice: 95, isCustomizable: true, iconKey: 'candles',
    shortDescription: 'ההדלקה הראשונה שלה: פמוט מעוצב לילדה בגוון ורוד-פנינה עם חריטת שם.',
    longDescription: ['פמוט אישי לילדה שמתחילה להדליק נר שבת — גימור ורוד-פנינה עדין עם נקודות לבנות ובסיס יציב ובטוח. חריטת השם הופכת אותו לשלה באמת. מתנה מסורתית מסבתא לנכדה.'],
    materials: ['מתכת', 'גימור פנינה'], dimensions: 'גובה 14 ס"מ',
    prepTimeDays: [3, 6], tags: ['ילדות', 'הדלקה ראשונה', 'חריטה אישית', 'מתנה'],
    relatedSlugs: ['kiddush-kids-cup', 'necklace-kids-hamsa', 'candlesticks-crystal-or'],
    stockStatus: 'in-stock', badges: ['recommended'], audience: ['kids'],
    customization: { ...ENGRAVING_SILVER, maxChars: 12, surcharges: { text: 0, symbol: 15, logo: 0, giftWrap: 15 } },
  }),
  def({
    id: 'x25', sku: 'EB-CS-104', slug: 'candle-tray-tempered',
    titleHe: 'מגש נרות מזכוכית מחוסמת', imageUrl: `${IMG}/candle-tray.svg`,
    category: 'פמוטים', subcategory: 'מגשים ואביזרים',
    material: 'זכוכית מחוסמת, פס זהב', basePrice: 150, isCustomizable: false, iconKey: 'candles',
    shortDescription: 'בסיס בטוח ויפה לנרות: זכוכית מחוסמת עמידת חום עם פס זהב מודפס.',
    longDescription: ['מגש נרות מזכוכית מחוסמת עמידה בחום, שמגן על השיש ומוסיף מסגרת מעוצבת להדלקה. קל לניקוי משעווה, עם פס זהב היקפי. מתאים לפמוטים וגם לכוסיות נרונים.'],
    materials: ['זכוכית מחוסמת'], dimensions: '38×24 ס"מ',
    prepTimeDays: [1, 3], tags: ['אביזר', 'בטיחות', 'שבת'],
    relatedSlugs: ['candlesticks-modern-silver', 'candlesticks-crystal-or', 'candlestick-girl-first'],
    stockStatus: 'in-stock', badges: [],
  }),

  // ================= תשמישי קדושה לבית =================
  def({
    id: 'x26', sku: 'EB-MZ-101', slug: 'mezuzah-aluminum-modern',
    titleHe: 'בית מזוזה אלומיניום — קו מודרני', imageUrl: `${IMG}/mezuzah-aluminum.svg`,
    category: 'תשמישי קדושה לבית', subcategory: 'מזוזות',
    material: 'אלומיניום מוברש', basePrice: 120, isCustomizable: true, iconKey: 'mezuzah',
    shortDescription: 'נקי, גיאומטרי ועמיד לחוץ: בית מזוזה מאלומיניום מוברש לבתים מודרניים.',
    longDescription: ['בית מזוזה בקו נקי מאלומיניום מוברש, עמיד למזג אוויר ומתאים גם לדלת הכניסה. פס אור מוברש לאורך הגוף ו-ש׳ חרוטה. אפשר להוסיף קלף מהודר בבדיקה כפולה.'],
    materials: ['אלומיניום'], dimensions: 'לקלף 12 ס"מ',
    prepTimeDays: [1, 3], tags: ['מודרני', 'עמיד לחוץ', 'בית חדש'],
    relatedSlugs: ['mezuzah-klaf-beit-yosef-12', 'mezuzah-jerusalem-stone', 'gift-set-new-home'],
    stockStatus: 'in-stock', badges: ['bestseller'], occasions: ['בית חדש'],
    variantGroups: [{ id: 'klaf', label: 'קלף', options: [
      { id: 'without', label: 'בית בלבד', priceDelta: 0 }, { id: 'with', label: 'עם קלף מהודר', priceDelta: 260 },
    ]}],
    customization: { ...ENGRAVING_SILVER, maxChars: 14, positions: [{ id: 'front', label: 'לאורך הבית' }], surcharges: { text: 45, symbol: 0, logo: 0, giftWrap: 20 } },
  }),
  def({
    id: 'x27', sku: 'EB-MZ-102', slug: 'mezuzah-jerusalem-stone',
    titleHe: 'בית מזוזה מאבן ירושלמית', imageUrl: `${IMG}/mezuzah-stone.svg`,
    category: 'תשמישי קדושה לבית', subcategory: 'מזוזות',
    material: 'אבן ירושלמית מסותתת', basePrice: 240, isCustomizable: false, iconKey: 'mezuzah',
    shortDescription: 'חתיכה מירושלים על המשקוף: אבן ירושלמית אמיתית מסותתת ביד.',
    longDescription: ['בית מזוזה מסותת מאבן ירושלמית אמיתית — כל בית בגוון ובטקסטורה מעט שונים, כי כך זה באבן טבעית. עמיד לחלוטין לחוץ. מתנה סמלית עם חיבור אמיתי לארץ ישראל.'],
    materials: ['אבן ירושלמית'], dimensions: 'לקלף 12 ס"מ',
    prepTimeDays: [4, 8], tags: ['אבן ירושלמית', 'עבודת יד', 'בית חדש'],
    relatedSlugs: ['mezuzah-aluminum-modern', 'jerusalem-wall-art-gold', 'gift-set-new-home'],
    stockStatus: 'in-stock', badges: ['handmade'], occasions: ['בית חדש'],
  }),
  def({
    id: 'x28', sku: 'EB-MZ-103', slug: 'mezuzah-ceramic-kids',
    titleHe: 'בית מזוזה קרמיקה לחדר ילדים', imageUrl: `${IMG}/mezuzah-ceramic-kids.svg`,
    category: 'תשמישי קדושה לבית', subcategory: 'מזוזות',
    material: 'קרמיקה צבועה ביד', basePrice: 85, isCustomizable: false, iconKey: 'mezuzah',
    shortDescription: 'מזוזה שילדים אוהבים: קרמיקה בטורקיז שמח עם ציורי פרחים — צבועה ביד.',
    longDescription: ['בית מזוזה מקרמיקה בצבע טורקיז עליז עם עיטורי פרחים לבנים, צבוע ביד. גימור מבריק ועמיד. הופך את הקבע של חדר הילדים למשהו ששלהם.'],
    materials: ['קרמיקה'], dimensions: 'לקלף 10 ס"מ',
    prepTimeDays: [2, 5], tags: ['ילדים', 'קרמיקה', 'צבעוני'],
    relatedSlugs: ['mezuzah-aluminum-modern', 'kippah-kids-colorful', 'gift-baby-mazal'],
    stockStatus: 'in-stock', badges: ['new'], audience: ['kids'], occasions: ['יולדת', 'בית חדש'],
  }),
  def({
    id: 'x29', sku: 'EB-HL-101', slug: 'honey-dish-apple-glass',
    titleHe: 'כלי דבש "תפוח" מזכוכית על מגש', imageUrl: `${IMG}/honey-dish.svg`,
    category: 'תשמישי קדושה לבית', subcategory: 'ראש השנה',
    material: 'זכוכית בעבודת יד + כף עץ', basePrice: 190, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'שתהא השנה מתוקה: כלי דבש בצורת תפוח מזכוכית ענבר, עם כף טבילה ומגש.',
    longDescription: ['כלי דבש בצורת תפוח מזכוכית בגוון ענבר חם, עם עלה ירוק, כף עץ ומגש כסוף תואם. מרכז שולחן מושלם לראש השנה ומתנה מתוקה למארחים.'],
    materials: ['זכוכית', 'כף עץ', 'מגש בציפוי כסף'], dimensions: 'קוטר 14 ס"מ',
    prepTimeDays: [2, 5], tags: ['ראש השנה', 'דבש', 'מתנה למארחים'],
    relatedSlugs: ['shofar-ram-polished-classic', 'gift-hostess-shabbat', 'seder-plate-silver-six'],
    stockStatus: 'in-stock', badges: ['bestseller'], occasions: ['חג'],
  }),
  def({
    id: 'x30', sku: 'EB-PS-101', slug: 'seder-plate-silver-six',
    titleHe: 'קערת פסח מהודרת עם 6 קעריות', imageUrl: `${IMG}/seder-plate.svg`,
    category: 'תשמישי קדושה לבית', subcategory: 'פסח',
    material: 'ציפוי כסף, קעריות נשלפות', basePrice: 380, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'ליל הסדר מסודר: קערה מרכזית עם שש קעריות נשלפות לסימנים ומגן דוד מוזהב.',
    longDescription: ['קערת פסח בציפוי כסף עם שש קעריות נשלפות לסימני הסדר — נוחות להגשה ולניקוי. עיטור מגן דוד מוזהב במרכז. אפשרות לחריטת שם משפחה בשוליים.'],
    materials: ['ציפוי כסף'], dimensions: 'קוטר 35 ס"מ',
    prepTimeDays: [3, 7], tags: ['פסח', 'ליל הסדר', 'חריטה אישית'],
    relatedSlugs: ['eliyahu-cup-gilded', 'kiddush-set-six-cups', 'honey-dish-apple-glass'],
    stockStatus: 'in-stock', badges: ['recommended'], occasions: ['חג'], audience: ['family'],
    customization: { ...ENGRAVING_SILVER, positions: [{ id: 'base', label: 'שולי הקערה' }] },
  }),

  // ================= מתנות ואירועים =================
  def({
    id: 'x31', sku: 'EB-GF-101', slug: 'gift-set-new-home',
    titleHe: 'מארז חנוכת בית — מזוזה, ברכה ונטלה', imageUrl: `${IMG}/gift-new-home.svg`,
    category: 'מתנות ואירועים', subcategory: 'מארזים',
    material: 'מארז קופסה מהודר', basePrice: 390, discountPrice: 350, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'המתנה השלמה לבית חדש: בית מזוזה, ברכת הבית ממוסגרת ונטלה — במארז אחד.',
    longDescription: ['שלושת הפריטים שכל בית חדש צריך, ארוזים יחד בקופסת מתנה כחולה עם סרט זהב: בית מזוזה מאלומיניום (בלי קלף — לבחירת המקבל), ברכת הבית מודפסת וממוסגרת, ונטלה. אפשר לצרף כרטיס ברכה אישי מודפס.'],
    materials: ['ראו פריטים בודדים'], prepTimeDays: [2, 5],
    tags: ['בית חדש', 'מארז', 'מתנה מוכנה'],
    relatedSlugs: ['mezuzah-aluminum-modern', 'birkat-habait-framed', 'natla-silver-engraved'],
    stockStatus: 'in-stock', badges: ['bestseller'], occasions: ['בית חדש'], audience: ['family'],
    customization: { ...PRINT_PERSONAL, maxChars: 60, positions: [{ id: 'bottom', label: 'כרטיס ברכה מצורף' }] },
  }),
  def({
    id: 'x32', sku: 'EB-GF-102', slug: 'barmitzvah-complete-set',
    titleHe: 'מארז בר מצווה מלא — טלית, תפילין ותיק', imageUrl: `${IMG}/barmitzvah-set.svg`,
    category: 'מתנות ואירועים', subcategory: 'בר מצווה',
    material: 'סט מתואם מלא', basePrice: 2400, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'הכול מוכן ליום הגדול: טלית עם רקמת שם, תפילין מהודרות ותיק קטיפה תואם.',
    longDescription: ['המארז שחוסך את ההתרוצצות: טלית אקרילן או צמר (לבחירה), תפילין בכתב בית יוסף עם תעודת בדיקה, ותיק קטיפה עם רקמת שם הנער — הכול מתואם ומוכן ליום הבר מצווה.', 'הרכבת הסט מלווה בייעוץ אישי בוואטסאפ להתאמת הנוסח, המידה והקשירה.'],
    materials: ['ראו פריטים בודדים'], prepTimeDays: [12, 21],
    tags: ['בר מצווה', 'סט מלא', 'רקמה אישית'],
    relatedSlugs: ['tallit-acrylic-barmitzvah', 'tefillin-beit-yosef-mehudarot', 'tallit-bag-velvet-embroidery'],
    stockStatus: 'made-to-order', badges: ['luxury', 'recommended'], occasions: ['בר מצווה'], audience: ['kids', 'men'],
    variantGroups: [{ id: 'tallit-type', label: 'סוג הטלית', options: [
      { id: 'acrylic', label: 'אקרילן', priceDelta: 0 }, { id: 'wool', label: 'צמר', priceDelta: 500 },
    ]}],
    customization: TALLIT_CUSTOMIZATION,
  }),
  def({
    id: 'x33', sku: 'EB-GF-103', slug: 'wedding-breaking-glass-set',
    titleHe: 'כוס שבירה לחתונה + נרתיק מזכרת', imageUrl: `${IMG}/breaking-glass.svg`,
    category: 'מתנות ואירועים', subcategory: 'חתונה',
    material: 'זכוכית + נרתיק קטיפה רקום', basePrice: 160, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'הרגע של "אם אשכחך" — כוס לשבירה ונרתיק קטיפה לשמירת הרסיסים למזכרת.',
    longDescription: ['סט לרגע המרגש בחופה: כוס זכוכית דקה לשבירה בטוחה, ונרתיק קטיפה כחול עם רקמת מגן דוד לאיסוף הרסיסים — שהופכים למזכרת מהיום הגדול. אפשר לרקום את שמות בני הזוג והתאריך על הנרתיק.'],
    materials: ['זכוכית', 'קטיפה'], prepTimeDays: [3, 7],
    tags: ['חתונה', 'חופה', 'מזכרת', 'רקמה אישית'],
    relatedSlugs: ['ketubah-art-print', 'kiddush-cup-jerusalem-925', 'kippot-event-branded'],
    stockStatus: 'in-stock', badges: ['bestseller'], occasions: ['חתונה'],
    customization: { ...TALLIT_CUSTOMIZATION, maxChars: 24, positions: [{ id: 'front', label: 'חזית הנרתיק' }], surcharges: { text: 45, symbol: 20, logo: 0, giftWrap: 20 } },
  }),
  def({
    id: 'x34', sku: 'EB-GF-104', slug: 'ketubah-art-print',
    titleHe: 'כתובה מעוצבת — הדפסת אמנות עם שער ירושלים', imageUrl: `${IMG}/ketubah.svg`,
    category: 'מתנות ואירועים', subcategory: 'חתונה',
    material: 'הדפסת אמנות על נייר ללא חומצה', basePrice: 450, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'כתובה שהיא יצירת אמנות: עיטורי זהב ושער ירושלים, בהדפסה איכותית עם מילוי אישי.',
    longDescription: ['כתובה מעוצבת בהדפסת אמנות עם מסגרת עיטורים בזהב ומוטיב שער ירושלים. מודפסת על נייר ללא חומצה שנשמר לדורות. הנוסח לבחירה (אורתודוקסי/אחר) והשמות והתאריך ממולאים בהדפסה אישית לפני המשלוח.'],
    materials: ['נייר אמנות ללא חומצה', 'הדפסת פיגמנט'], dimensions: '50×40 ס"מ',
    prepTimeDays: [5, 10], tags: ['חתונה', 'כתובה', 'הדפסה אישית'],
    relatedSlugs: ['wedding-breaking-glass-set', 'birkat-habait-framed', 'jerusalem-wall-art-gold'],
    stockStatus: 'made-to-order', badges: ['exclusive'], occasions: ['חתונה'],
    variantGroups: [{ id: 'nusach', label: 'נוסח', options: [
      { id: 'orthodox', label: 'אורתודוקסי', priceDelta: 0 }, { id: 'custom', label: 'נוסח אישי (בתיאום)', priceDelta: 80 },
    ]}],
    customization: { ...PRINT_PERSONAL, maxChars: 60 },
  }),
  def({
    id: 'x35', sku: 'EB-GF-105', slug: 'gift-baby-mazal',
    titleHe: 'מארז מזל טוב ליולדת', imageUrl: `${IMG}/gift-baby.svg`,
    category: 'מתנות ואירועים', subcategory: 'מארזים',
    material: 'מארז קופסה בגוון שמנת', basePrice: 220, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'לחבק את המשפחה החדשה: בית מזוזה לחדר התינוק וברכת ילדים ממוסגרת, במארז רך.',
    longDescription: ['מארז ליולדת שמרגיש אישי: בית מזוזה מקרמיקה לחדר הילדים וברכת הבן/הבת ממוסגרת, ארוזים בקופסת שמנת עם סרט תכלת. מוסיפים כרטיס ברכה מודפס עם שם התינוק — והמתנה מוכנה.'],
    materials: ['ראו פריטים בודדים'], prepTimeDays: [2, 5],
    tags: ['יולדת', 'ברית', 'מארז', 'תינוק'],
    relatedSlugs: ['mezuzah-ceramic-kids', 'necklace-kids-hamsa', 'kiddush-kids-cup'],
    stockStatus: 'in-stock', badges: ['new'], occasions: ['יולדת'], audience: ['family'],
    customization: { ...PRINT_PERSONAL, maxChars: 40, positions: [{ id: 'bottom', label: 'כרטיס ברכה מצורף' }] },
  }),
  def({
    id: 'x36', sku: 'EB-GF-106', slug: 'gift-hostess-shabbat',
    titleHe: 'מארז מארחים לשבת', imageUrl: `${IMG}/gift-hostess.svg`,
    category: 'מתנות ואירועים', subcategory: 'מארזים',
    material: 'מארז קופסה טבעי', basePrice: 150, discountPrice: 129, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'במקום עוד בקבוק יין: כלי דבש קטן, מלחייה מעוצבת וגפרורים ארוכים — מארז אירוח מושלם.',
    longDescription: ['המתנה שמביאים כשמתארחים בשבת: כלי דבש מיני מזכוכית, מלחייה מעוצבת וקופסת גפרורים ארוכים — ארוזים יפה ומוכנים לנתינה. מחיר נעים, רושם גדול.'],
    materials: ['זכוכית', 'מתכת'], prepTimeDays: [1, 3],
    tags: ['מארחים', 'שבת', 'מתנה קטנה'],
    relatedSlugs: ['honey-dish-apple-glass', 'candle-tray-tempered', 'scarf-duo-giftbox'],
    stockStatus: 'in-stock', badges: ['bestseller'], occasions: ['שבת'],
  }),
  def({
    id: 'x37', sku: 'EB-GF-107', slug: 'corporate-gifts-branded',
    titleHe: 'מתנות ממותגות לעסקים ומוסדות', imageUrl: `${IMG}/gift-new-home.svg`,
    category: 'מתנות ואירועים', subcategory: 'לעסקים ומוסדות',
    material: 'לפי בחירת המוצרים', basePrice: 0, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'מתנות חג לעובדים וללקוחות עם מיתוג מלא — מרכיבים יחד מארז לפי תקציב.',
    longDescription: ['פתרון מתנות לארגונים: בוחרים מוצרים לפי תקציב (מארזי דבש, כלי קידוש, ספרים עם הטבעה), מוסיפים לוגו וכרטיס ממותג — ואנחנו אורזים ומספקים עד המשרד. מתאים לראש השנה, פסח ואירועי חברה. השאירו פרטים ונחזור עם הצעה מותאמת.'],
    materials: ['לפי בחירה'], prepTimeDays: [14, 30],
    tags: ['עסקים', 'מוסדות', 'מתנות לעובדים', 'לוגו', 'הזמנה בכמות'],
    relatedSlugs: ['kippot-event-branded', 'honey-dish-apple-glass', 'siddur-leather-custom-emboss'],
    stockStatus: 'made-to-order', badges: [], priceType: 'quote', audience: ['family'],
  }),

  // ================= תכשיטי יודאיקה =================
  def({
    id: 'x38', sku: 'EB-JW-101', slug: 'necklace-magen-david-silver',
    titleHe: 'שרשרת מגן דוד — כסף 925', imageUrl: `${IMG}/necklace-magen-silver.svg`,
    category: 'תכשיטי יודאיקה', subcategory: 'שרשראות',
    material: 'כסף סטרלינג 925', basePrice: 240, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'הקלאסיקה שתמיד נכונה: מגן דוד עדין מכסף 925 על שרשרת תואמת.',
    longDescription: ['תליון מגן דוד מכסף סטרלינג 925 בעיצוב קווי נקי, על שרשרת כסף באורך מתכוונן. עמיד למים ולשימוש יומיומי. מגיע בקופסת מתנה.'],
    materials: ['כסף סטרלינג 925'], dimensions: 'תליון 18 מ"מ · שרשרת 45 ס"מ',
    prepTimeDays: [1, 3], tags: ['כסף 925', 'מגן דוד', 'מתנה'],
    relatedSlugs: ['necklace-chai-gold-14k', 'bracelet-hamsa-silver', 'necklace-magen-david-men'],
    stockStatus: 'in-stock', badges: ['bestseller'], audience: ['women', 'men'],
  }),
  def({
    id: 'x39', sku: 'EB-JW-102', slug: 'necklace-chai-gold-14k',
    titleHe: 'שרשרת "חי" — זהב 14K', imageUrl: `${IMG}/necklace-chai-gold.svg`,
    category: 'תכשיטי יודאיקה', subcategory: 'שרשראות',
    material: 'זהב צהוב 14 קראט', basePrice: 1150, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'מילה אחת, משמעות שלמה: תליון "חי" מזהב 14K אמיתי על שרשרת זהב.',
    longDescription: ['תליון "חי" מזהב צהוב 14 קראט מלא (לא ציפוי), בחיתוך מוקפד עם גימור מבריק, על שרשרת זהב תואמת. תכשיט לדורות שמגיע עם תעודת אחריות ובקופסת מתנה מהודרת.'],
    materials: ['זהב 14K'], dimensions: 'תליון 15 מ"מ · שרשרת 42 ס"מ',
    prepTimeDays: [3, 7], tags: ['זהב', 'חי', 'מתנה יוקרתית'],
    relatedSlugs: ['necklace-magen-david-silver', 'pendant-jerusalem-gilded', 'necklace-magen-david-men'],
    stockStatus: 'in-stock', badges: ['luxury'], audience: ['women'],
  }),
  def({
    id: 'x40', sku: 'EB-JW-103', slug: 'bracelet-hamsa-silver',
    titleHe: 'צמיד חמסה עדין — כסף 925', imageUrl: `${IMG}/bracelet-hamsa.svg`,
    category: 'תכשיטי יודאיקה', subcategory: 'צמידים',
    material: 'כסף סטרלינג 925', basePrice: 180, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'שמירה על היד: צמיד כסף עדין עם תליון חמסה קטן — מתנה שמתאימה לכולן.',
    longDescription: ['צמיד כסף 925 עדין עם תליון חמסה מיניאטורי. סוגר קפיצי נוח ואורך מתכוונן. מתנה קלאסית לבת מצווה, ליום הולדת ולכלה.'],
    materials: ['כסף סטרלינג 925'], dimensions: 'אורך 16–19 ס"מ',
    prepTimeDays: [1, 3], tags: ['חמסה', 'צמיד', 'בת מצווה'],
    relatedSlugs: ['necklace-magen-david-silver', 'necklace-kids-hamsa', 'hamsa-ceramic-wall'],
    stockStatus: 'in-stock', badges: ['recommended'], audience: ['women', 'kids'],
  }),
  def({
    id: 'x41', sku: 'EB-JW-104', slug: 'pendant-jerusalem-gilded',
    titleHe: 'תליון ירושלים של זהב', imageUrl: `${IMG}/pendant-jerusalem.svg`,
    category: 'תכשיטי יודאיקה', subcategory: 'שרשראות',
    material: 'כסף בציפוי זהב', basePrice: 320, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'קו הרקיע של ירושלים חרוט על מטבע זהוב — תליון עם סיפור.',
    longDescription: ['תליון עגול בציפוי זהב עם תחריט קו הרקיע של ירושלים העתיקה — החומות, המגדלים והכיפות. על שרשרת תואמת. מתנה מרגשת לעולים, לתיירים ולכל מי שליבו בירושלים.'],
    materials: ['כסף 925 בציפוי זהב'], dimensions: 'תליון 22 מ"מ',
    prepTimeDays: [2, 5], tags: ['ירושלים', 'תליון', 'מתנה'],
    relatedSlugs: ['jerusalem-wall-art-gold', 'necklace-chai-gold-14k', 'necklace-magen-david-silver'],
    stockStatus: 'in-stock', badges: ['exclusive'], audience: ['women', 'men'],
  }),
  def({
    id: 'x42', sku: 'EB-JW-105', slug: 'necklace-magen-david-men',
    titleHe: 'שרשרת מגן דוד לגבר — מוזהבת', imageUrl: `${IMG}/necklace-magen-men.svg`,
    category: 'תכשיטי יודאיקה', subcategory: 'לגברים',
    material: 'כסף בציפוי זהב, עובי מוגבר', basePrice: 280, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'נוכחות גברית: מגן דוד בחיתוך עבה על שרשרת חוליות חזקה.',
    longDescription: ['מגן דוד לגברים בחיתוך עבה ובולט, בציפוי זהב על כסף, עם שרשרת חוליות עמידה באורך 55 ס"מ. עמיד לשימוש יומיומי ולספורט.'],
    materials: ['כסף בציפוי זהב'], dimensions: 'תליון 25 מ"מ · שרשרת 55 ס"מ',
    prepTimeDays: [1, 3], tags: ['לגברים', 'מגן דוד'],
    relatedSlugs: ['necklace-magen-david-silver', 'kippah-leather-handmade', 'pendant-jerusalem-gilded'],
    stockStatus: 'in-stock', badges: [], audience: ['men'],
  }),
  def({
    id: 'x43', sku: 'EB-JW-106', slug: 'necklace-kids-hamsa',
    titleHe: 'שרשרת חמסה לילדה — מוזהבת', imageUrl: `${IMG}/necklace-kids.svg`,
    category: 'תכשיטי יודאיקה', subcategory: 'לילדים',
    material: 'ציפוי זהב היפואלרגני', basePrice: 120, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'התכשיט הראשון שלה: חמסה קטנה ומוזהבת על שרשרת באורך ילדות.',
    longDescription: ['שרשרת לילדות עם תליון חמסה קטן בציפוי זהב היפואלרגני, באורך מותאם (38 ס"מ) עם סוגר בטיחותי. מתנה מתוקה לבת מצווה קטנה, לסידור ראשון וליום הולדת.'],
    materials: ['ציפוי זהב היפואלרגני'], dimensions: 'תליון 12 מ"מ · שרשרת 38 ס"מ',
    prepTimeDays: [1, 3], tags: ['ילדים', 'חמסה', 'מתנה'],
    relatedSlugs: ['bracelet-hamsa-silver', 'candlestick-girl-first', 'mezuzah-ceramic-kids'],
    stockStatus: 'in-stock', badges: ['new'], audience: ['kids'],
  }),

  // ================= אמנות ועיצוב =================
  def({
    id: 'x44', sku: 'EB-AR-101', slug: 'birkat-habait-framed',
    titleHe: 'ברכת הבית ממוסגרת — קלאסית', imageUrl: `${IMG}/birkat-habait.svg`,
    category: 'אמנות ועיצוב יהודי', subcategory: 'ברכות הבית',
    material: 'הדפס אמנות במסגרת עץ', basePrice: 180, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'הברכה שפותחת כל בית: הדפס מעוצב עם עיטורי זהב במסגרת כחולה עמוקה.',
    longDescription: ['ברכת הבית המסורתית בעיצוב קליגרפי עם קשת עיטורים בזהב, מודפסת על נייר אמנות וממוסגרת במסגרת עץ כחולה. אפשר להוסיף בהדפסה את שם המשפחה בשורת ההקדשה — מתנה מושלמת לחנוכת בית.'],
    materials: ['נייר אמנות', 'מסגרת עץ', 'זכוכית'], dimensions: '30×40 ס"מ',
    prepTimeDays: [3, 6], tags: ['ברכת הבית', 'בית חדש', 'הדפסה אישית'],
    relatedSlugs: ['gift-set-new-home', 'psukim-print-custom', 'mezuzah-aluminum-modern'],
    stockStatus: 'in-stock', badges: ['bestseller'], occasions: ['בית חדש'],
    customization: { ...PRINT_PERSONAL, maxChars: 20 },
  }),
  def({
    id: 'x45', sku: 'EB-AR-102', slug: 'jerusalem-wall-art-gold',
    titleHe: 'קו רקיע ירושלים — הדפס זהב על לילה', imageUrl: `${IMG}/jerusalem-wall-art.svg`,
    category: 'אמנות ועיצוב יהודי', subcategory: 'אמנות קיר',
    material: 'הדפס פיגמנט זהב, מסגרת זהב', basePrice: 520, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'ירושלים בקו אחד של זהב: העיר העתיקה על רקע כחול לילה, במסגרת מוזהבת.',
    longDescription: ['הדפס אמנות בקו-מתאר זהב של העיר העתיקה — החומות, המגדלים והכיפות — על רקע כחול לילה עמוק. מסגרת בגימור זהב. מהדורה ממוספרת של 100 עותקים.'],
    materials: ['נייר אמנות', 'הדפסת פיגמנט', 'מסגרת מוזהבת'], dimensions: '40×40 ס"מ',
    prepTimeDays: [4, 8], tags: ['ירושלים', 'אמנות קיר', 'מהדורה מוגבלת'],
    relatedSlugs: ['pendant-jerusalem-gilded', 'birkat-habait-framed', 'shema-glass-art'],
    stockStatus: 'in-stock', badges: ['limited', 'exclusive'], stockLeft: 3,
  }),
  def({
    id: 'x46', sku: 'EB-AR-103', slug: 'hamsa-ceramic-wall',
    titleHe: 'חמסה קרמיקה כחולה לתלייה', imageUrl: `${IMG}/hamsa-ceramic.svg`,
    category: 'אמנות ועיצוב יהודי', subcategory: 'חמסות',
    material: 'קרמיקה צבועה ביד', basePrice: 140, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'חמסה גדולה מקרמיקה בכחול ים, צבועה ביד — שמירה יפה לכל קיר.',
    longDescription: ['חמסת קיר מקרמיקה בגוון כחול-ים עם עין לבנה ועיטורים, צבועה ביד וצרובה בתנור. טבעת תלייה מוזהבת בחלקה העליון. כל חמסה מעט שונה — כי כך זה בעבודת יד.'],
    materials: ['קרמיקה'], dimensions: 'גובה 22 ס"מ',
    prepTimeDays: [2, 5], tags: ['חמסה', 'קרמיקה', 'עבודת יד'],
    relatedSlugs: ['hamsa-silver-wall-limited', 'bracelet-hamsa-silver', 'birkat-habait-framed'],
    stockStatus: 'in-stock', badges: ['handmade'],
  }),
  def({
    id: 'x47', sku: 'EB-AR-104', slug: 'hamsa-silver-wall-limited',
    titleHe: 'חמסת קיר מכסף — מהדורה מוגבלת', imageUrl: `${IMG}/hamsa-silver.svg`,
    category: 'אמנות ועיצוב יהודי', subcategory: 'חמסות',
    material: 'ציפוי כסף על נחושת, עבודת אומן', basePrice: 780, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'חמסת אומן מכסף עם עין זהב — מהדורה מוגבלת וממוספרת.',
    longDescription: ['חמסת קיר בעבודת אומן: גוף כסוף מבריק עם חריטת עיטורים ועין מרכזית בזהב. מהדורה מוגבלת וממוספרת. מגיעה במארז עם תעודת מהדורה.'],
    materials: ['נחושת בציפוי כסף', 'עיטור זהב'], dimensions: 'גובה 26 ס"מ',
    prepTimeDays: [7, 14], tags: ['חמסה', 'עבודת יד', 'מהדורה מוגבלת', 'אספנות'],
    relatedSlugs: ['hamsa-ceramic-wall', 'torah-rimonim-silver-bells', 'jerusalem-wall-art-gold'],
    stockStatus: 'made-to-order', badges: ['limited', 'handmade', 'luxury'],
  }),
  def({
    id: 'x48', sku: 'EB-AR-105', slug: 'psukim-print-custom',
    titleHe: 'פסוק מעוצב ממוסגר — לבחירתכם', imageUrl: `${IMG}/psukim-print.svg`,
    category: 'אמנות ועיצוב יהודי', subcategory: 'פסוקים מעוצבים',
    material: 'הדפס קליגרפי במסגרת עץ', basePrice: 260, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'הפסוק שמלווה אתכם — בקליגרפיה מעוצבת וממוסגרת, עם שורת הקדשה אישית.',
    longDescription: ['בוחרים פסוק מהרשימה (או מציעים משלכם בהערות) — ואנחנו מעצבים אותו בקליגרפיה עברית עם עיטורי זהב, מדפיסים על נייר אמנות וממסגרים בעץ אלון. שורת הקדשה אישית בתחתית הופכת אותו למתנה של פעם בחיים.'],
    materials: ['נייר אמנות', 'מסגרת אלון'], dimensions: '30×40 ס"מ',
    prepTimeDays: [5, 10], tags: ['פסוקים', 'הדפסה אישית', 'מתנה'],
    relatedSlugs: ['birkat-habait-framed', 'shema-glass-art', 'ketubah-art-print'],
    stockStatus: 'made-to-order', badges: ['recommended'],
    variantGroups: [{ id: 'verse', label: 'הפסוק', options: [
      { id: 'ish', label: 'איש ואישה — שכינה ביניהם', priceDelta: 0 },
      { id: 'hine', label: 'הנה מה טוב ומה נעים', priceDelta: 0 },
      { id: 'oz', label: 'עוז והדר לבושה', priceDelta: 0 },
      { id: 'custom', label: 'פסוק לבחירתי (בהערות)', priceDelta: 40 },
    ]}],
    customization: { ...PRINT_PERSONAL, maxChars: 30 },
  }),
  def({
    id: 'x49', sku: 'EB-AR-106', slug: 'shema-glass-art',
    titleHe: '"שמע ישראל" — אמנות על זכוכית', imageUrl: `${IMG}/shema-glass.svg`,
    category: 'אמנות ועיצוב יהודי', subcategory: 'אמנות קיר',
    material: 'הדפסה על זכוכית מחוסמת', basePrice: 940, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'מילות השמע צפות על זכוכית: הדפסת אמנות על זכוכית מחוסמת עם תלייה נסתרת.',
    longDescription: ['יצירת קיר מרשימה: קליגרפיית "שמע ישראל" מודפסת ישירות על זכוכית מחוסמת בעומק, עם מערכת תלייה נסתרת שגורמת ליצירה "לצוף" על הקיר. פריט מרכזי לסלון ולמשרד.'],
    materials: ['זכוכית מחוסמת 6 מ"מ', 'תלייה נסתרת'], dimensions: '60×40 ס"מ',
    prepTimeDays: [7, 14], tags: ['אמנות קיר', 'זכוכית', 'יוקרתי'],
    relatedSlugs: ['jerusalem-wall-art-gold', 'psukim-print-custom', 'hamsa-silver-wall-limited'],
    stockStatus: 'made-to-order', badges: ['luxury'],
  }),
];
