// ============================================================
// הקטלוג המורחב — אצווה 2 (y1–y32): ספרים, חגים, ילדים, בית כנסת ועוד.
// ⚠️ תוכן המחשה עד קבלת סחורה אמיתית. עריכה: אובייקט אחד למוצר.
// תמונות: scripts/generate-images-2.mjs
// ============================================================

import type { CatalogProduct } from '@/lib/catalog';
import {
  ENGRAVING_SILVER,
  EMBOSS_LEATHER,
  PRINT_PERSONAL,
} from '@/lib/customization-presets';

const IMG = '/images/products';

type ProductInput = Omit<CatalogProduct, 'gallery' | 'isPlaceholderImage'> &
  Partial<Pick<CatalogProduct, 'gallery' | 'isPlaceholderImage'>>;

function def(data: ProductInput): CatalogProduct {
  const src = data.imageUrl!;
  return {
    isPlaceholderImage: true,
    gallery: [
      { src, label: 'מבט ראשי' },
      { src, label: 'תקריב', zoom: 1.7 },
      { src, label: 'פרט עיצוב', zoom: 2.4 },
    ],
    ...data,
  };
}

export const EXTENDED_PRODUCTS_2: CatalogProduct[] = [
  // ================= ספרים וסידורים =================
  def({
    id: 'y1', sku: 'EB-BK-201', slug: 'siddur-pocket-leather-brown',
    titleHe: 'סידור עור כיס עם הטבעת שם', imageUrl: `${IMG}/siddur-pocket-brown.svg`,
    category: 'ספרים וסידורים', subcategory: 'סידורים',
    material: 'כריכת עור אמיתי, דפי שוליים מוזהבים', basePrice: 89, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'סידור כיס בכריכת עור רך, עם סימנייה והטבעת שם בזהב — מתנה שמלווה כל תפילה.',
    longDescription: [
      'סידור בגודל כיס בכריכת עור אמיתי רך, עם דפי שוליים מוזהבים וסימנייה תפורה. זמין בנוסח אשכנז, ספרד ועדות המזרח.',
      'ניתן להטביע שם בפויל זהב על הכריכה — מתנה קלאסית לבר מצווה, לחתן ולעדי קידושין.',
    ],
    materials: ['עור אמיתי', 'דפים בשוליים מוזהבים'], dimensions: '10×14 ס"מ',
    prepTimeDays: [2, 5], careInstructions: 'להרחיק מלחות ושמש ישירה.',
    tags: ['סידור', 'עור', 'הטבעת שם', 'בר מצווה'], relatedSlugs: ['tehillim-mini-pocket-gold', 'siddur-leather-custom-emboss', 'chumash-rashi-set-classic'],
    stockStatus: 'in-stock', badges: ['bestseller'], audience: ['men', 'family'], occasions: ['בר מצווה', 'חתונה'],
    variantGroups: [{ id: 'nusach', label: 'נוסח', options: [
      { id: 'ashkenaz', label: 'אשכנז', priceDelta: 0 }, { id: 'sefard', label: 'ספרד', priceDelta: 0 }, { id: 'edot', label: 'עדות המזרח', priceDelta: 0 },
    ]}, { id: 'color', label: 'צבע עור', options: [
      { id: 'brown', label: 'חום', priceDelta: 0, hex: '#6B4423' }, { id: 'black', label: 'שחור', priceDelta: 0, hex: '#1A1A1E' }, { id: 'navy', label: 'כחול', priceDelta: 10, hex: '#1B2A5E' },
    ]}],
    customization: EMBOSS_LEATHER,
  }),
  def({
    id: 'y2', sku: 'EB-BK-202', slug: 'tehillim-mini-pocket-gold',
    titleHe: 'תהילים כיס מוזהב', imageUrl: `${IMG}/tehillim-mini-blue.svg`,
    category: 'ספרים וסידורים', subcategory: 'תהילים',
    material: 'כריכה קשה, שוליים מוזהבים', basePrice: 39, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'ספר תהילים קטן להחזקה בכיס או בתיק — כריכה קשה עמידה ושוליים מוזהבים.',
    longDescription: ['ספר תהילים במהדורת כיס עם כריכה קשה עמידה ושוליים מוזהבים. אותיות ברורות וגדולות יחסית לגודל. מלווה ברגעים של בקשה, הודיה ושמחה.'],
    materials: ['כריכה קשה מצופה'], dimensions: '7×10 ס"מ',
    prepTimeDays: [1, 2], tags: ['תהילים', 'כיס', 'מתנה נגישה'], relatedSlugs: ['siddur-pocket-leather-brown', 'benching-set-event-10', 'tehillim-silver-podium'],
    stockStatus: 'in-stock', badges: [], audience: ['family'], occasions: ['שבת'],
  }),
  def({
    id: 'y3', sku: 'EB-BK-203', slug: 'chumash-rashi-set-classic',
    titleHe: 'חומש עם פירוש רש"י — מהדורה מהודרת', imageUrl: `${IMG}/chumash-rashi-set.svg`,
    category: 'ספרים וסידורים', subcategory: 'חומשים',
    material: 'כריכה קשה מהודרת, נייר איכותי', basePrice: 129, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'חמישה חומשי תורה עם פירוש רש"י, בכריכה מהודרת ובאותיות גדולות וברורות.',
    longDescription: ['מהדורת חומש מהודרת הכוללת את חמשת חומשי התורה עם פירוש רש"י, טעמי המקרא וניקוד מלא. הדפסה איכותית על נייר משובח, לבית הכנסת ולבית.'],
    materials: ['כריכה קשה', 'נייר משובח'], dimensions: '17×24 ס"מ',
    prepTimeDays: [1, 3], tags: ['חומש', 'רש"י', 'לימוד'], relatedSlugs: ['siddur-pocket-leather-brown', 'haggadah-illustrated-deluxe', 'tehillim-silver-podium'],
    stockStatus: 'in-stock', badges: ['recommended'], audience: ['men', 'family'],
  }),
  def({
    id: 'y4', sku: 'EB-BK-204', slug: 'haggadah-illustrated-deluxe',
    titleHe: 'הגדה של פסח מאוירת', imageUrl: `${IMG}/haggadah-illustrated.svg`,
    category: 'ספרים וסידורים', subcategory: 'הגדות',
    material: 'כריכה קשה, איורים בצבע מלא', basePrice: 75, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'הגדה מאוירת בצבע מלא — טקסט ברור, איורים קלאסיים ופירוש קצר לליל הסדר.',
    longDescription: ['הגדה של פסח במהדורה מאוירת: טקסט מנוקד וברור, איורים בצבע מלא ופירוש קצר לצד הסדר. מתאימה לכל בני המשפחה סביב שולחן ליל הסדר.'],
    materials: ['כריכה קשה', 'הדפסת צבע'], dimensions: '20×27 ס"מ',
    prepTimeDays: [1, 3], tags: ['הגדה', 'פסח', 'ליל הסדר'], relatedSlugs: ['chumash-rashi-set-classic', 'seder-plate-silver-six', 'eliyahu-cup-gilded'],
    stockStatus: 'in-stock', badges: [], audience: ['family'], occasions: ['חג'],
  }),
  def({
    id: 'y5', sku: 'EB-BK-205', slug: 'birkon-personalized-event',
    titleHe: 'ברכון בעיצוב אישי לאירוע', imageUrl: `${IMG}/birkon-personalized.svg`,
    category: 'ספרים וסידורים', subcategory: 'ברכונים',
    material: 'כריכה רכה, הדפסת שמות', basePrice: 18, isCustomizable: true, iconKey: 'gift', priceType: 'from',
    shortDescription: 'ברכון מעוצב עם שמות בעלי השמחה והתאריך — מזכרת מושלמת לאורחי האירוע.',
    longDescription: ['ברכון (ברכת המזון) בכריכה מעוצבת, עם אפשרות להדפיס את שמות בעלי השמחה, התאריך וברכה אישית על השער. מתאים לחתונות, בר מצוות ובריתות. מחיר ליחידה יורד משמעותית בכמות.'],
    materials: ['כריכה רכה מודפסת'], dimensions: '12×17 ס"מ',
    prepTimeDays: [5, 10], tags: ['ברכון', 'עיצוב אישי', 'מזכרת', 'הזמנת כמות'], relatedSlugs: ['benching-set-event-10', 'kippot-event-branded', 'siddur-pocket-leather-brown'],
    stockStatus: 'made-to-order', badges: ['recommended'], audience: ['family'], occasions: ['חתונה', 'בר מצווה'],
    customization: { ...PRINT_PERSONAL, bulkDiscounts: [{ minQty: 30, pct: 20 }, { minQty: 100, pct: 35 }, { minQty: 300, pct: 45 }] },
  }),
  def({
    id: 'y6', sku: 'EB-BK-206', slug: 'benching-set-event-10',
    titleHe: 'מארז 10 ברכונים לאירוע', imageUrl: `${IMG}/birkon-personalized.svg`,
    category: 'ספרים וסידורים', subcategory: 'ברכונים',
    material: 'כריכה רכה, מארז אחיד', basePrice: 55, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'עשרה ברכונים אחידים במארז מסודר — פתרון נוח לשולחן החג או לאירוע קטן.',
    longDescription: ['מארז של עשרה ברכונים אחידים בכריכה נעימה, לשולחן שבת גדול, לאירוע משפחתי או לישיבה. להזמנות גדולות עם הדפסת שם — ראו "ברכון בעיצוב אישי".'],
    materials: ['כריכה רכה'], dimensions: '12×17 ס"מ (×10)',
    prepTimeDays: [1, 3], tags: ['ברכונים', 'מארז', 'שבת'], relatedSlugs: ['birkon-personalized-event', 'tehillim-mini-pocket-gold', 'kippot-event-branded'],
    stockStatus: 'in-stock', badges: [], audience: ['family'],
  }),
  def({
    id: 'y7', sku: 'EB-BK-207', slug: 'tehillim-silver-podium',
    titleHe: 'ספר תהילים בכריכת כסף לעמוד', imageUrl: `${IMG}/tehillim-silver-stand.svg`,
    category: 'ספרים וסידורים', subcategory: 'מהדורות יוקרה',
    material: 'כריכת כסף 925 בעבודת יד', basePrice: 450, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'תהילים בכריכת כסף מעוטרת — פריט הידור לעמוד בית הכנסת או למתנת הוקרה.',
    longDescription: ['ספר תהילים עם כריכת כסף 925 מעוטרת בעבודת יד, לעמוד השליח ציבור או כמתנת הוקרה מכובדת. ניתן לחרוט הקדשה על הכריכה.'],
    materials: ['כריכת כסף 925', 'גוף ספר איכותי'], dimensions: '14×20 ס"מ',
    prepTimeDays: [5, 12], careInstructions: 'לנקות את הכסף במטלית ייעודית.',
    tags: ['תהילים', 'כסף 925', 'הקדשה', 'הידור'], relatedSlugs: ['siddur-pocket-leather-brown', 'yad-torah-silver-pointer', 'torah-crown-silver-royal'],
    stockStatus: 'made-to-order', badges: ['luxury'], audience: ['men'], occasions: ['בר מצווה'],
    customization: { ...ENGRAVING_SILVER, positions: [{ id: 'front', label: 'חזית הכריכה' }] },
  }),

  // ================= חגים ומועדים =================
  def({
    id: 'y8', sku: 'EB-HG-208', slug: 'dreidel-silver-925-collectors',
    titleHe: 'סביבון כסף 925 אספנים', imageUrl: `${IMG}/dreidel-silver-925.svg`,
    category: 'חגים ומועדים', subcategory: 'חנוכה',
    material: 'כסף סטרלינג 925', basePrice: 180, isCustomizable: true, iconKey: 'candles',
    shortDescription: 'סביבון כסף מהודר עם האותיות נ-ג-ה-פ — פריט חנוכה שנשאר במשפחה.',
    longDescription: ['סביבון מכסף סטרלינג 925 עם האותיות נ-ג-ה-פ חרוטות, ומשקל נעים המאפשר סחרור יציב. פריט אספנות לחנוכה או מתנה מכובדת. ניתן לחרוט הקדשה על הבסיס.'],
    materials: ['כסף סטרלינג 925'], dimensions: 'גובה 7 ס"מ',
    prepTimeDays: [3, 7], tags: ['חנוכה', 'כסף 925', 'אספנות', 'חריטה'], relatedSlugs: ['dreidels-wood-family-set', 'hanukkiah-silver-925-mikdash', 'gift-hostess-shabbat'],
    stockStatus: 'in-stock', badges: ['luxury'], audience: ['family'], occasions: ['חג'],
    customization: { ...ENGRAVING_SILVER, positions: [{ id: 'base', label: 'בסיס' }] },
  }),
  def({
    id: 'y9', sku: 'EB-HG-209', slug: 'dreidels-wood-family-set',
    titleHe: 'מארז סביבוני עץ למשפחה', imageUrl: `${IMG}/dreidels-wood-set.svg`,
    category: 'חגים ומועדים', subcategory: 'חנוכה',
    material: 'עץ מלא, צביעה ידנית', basePrice: 35, isCustomizable: false, iconKey: 'candles',
    shortDescription: 'שלושה סביבוני עץ בגדלים שונים — חמים, מסורתיים ומושלמים למשחק משפחתי.',
    longDescription: ['מארז שלושה סביבוני עץ מלא בגדלים שונים, בצביעה ידנית עם האותיות המסורתיות. נעימים למגע ומסתובבים יפה — כיף לכל המשפחה בחנוכה.'],
    materials: ['עץ מלא', 'צבע על בסיס מים'], dimensions: 'גבהים 5–8 ס"מ',
    prepTimeDays: [1, 3], tags: ['חנוכה', 'עץ', 'ילדים', 'משחק'], relatedSlugs: ['dreidel-silver-925-collectors', 'alephbet-wooden-puzzle', 'shabbat-set-kids-starter'],
    stockStatus: 'in-stock', badges: ['bestseller'], audience: ['kids', 'family'], occasions: ['חג'],
  }),
  def({
    id: 'y10', sku: 'EB-HG-210', slug: 'etrog-box-silver-mehudar',
    titleHe: 'קופסת אתרוג מהודרת מכסף', imageUrl: `${IMG}/etrog-box-silver.svg`,
    category: 'חגים ומועדים', subcategory: 'סוכות',
    material: 'ציפוי כסף, ריפוד פנימי', basePrice: 340, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'קופסת אתרוג מרופדת עם עיטור כסף — שומרת על האתרוג מהודר לאורך כל החג.',
    longDescription: ['קופסת אתרוג בציפוי כסף עם עיטור מסורתי וריפוד פנימי רך המגן על האתרוג. סגירה יציבה ומראה מכובד לשולחן החג. ניתן לחרוט שם משפחה.'],
    materials: ['מתכת בציפוי כסף', 'ריפוד קטיפה'], dimensions: '14×11×10 ס"מ',
    prepTimeDays: [3, 7], careInstructions: 'לנקות במטלית יבשה.',
    tags: ['סוכות', 'אתרוג', 'כסף', 'חריטה'], relatedSlugs: ['arba-minim-set-mehadrin', 'honey-dish-apple-glass', 'rosh-hashana-plate-divided'],
    stockStatus: 'in-stock', badges: ['luxury', 'handmade'], audience: ['men', 'family'], occasions: ['חג'],
    customization: { ...ENGRAVING_SILVER, maxChars: 18 },
  }),
  def({
    id: 'y11', sku: 'EB-HG-211', slug: 'arba-minim-set-mehadrin',
    titleHe: 'סט ארבעת המינים מהדרין', imageUrl: `${IMG}/arba-minim-mehadrin.svg`,
    category: 'חגים ומועדים', subcategory: 'סוכות',
    material: 'לולב, הדס, ערבה ואתרוג מובחרים', basePrice: 180, isCustomizable: false, iconKey: 'gift', priceType: 'quote',
    shortDescription: 'סט ארבעת המינים בבחירה קפדנית — לולב, הדסים, ערבות ואתרוג, לפי דרגת ההידור.',
    longDescription: [
      'סט ארבעת המינים בבחירה קפדנית לקראת חג הסוכות: לולב ישר, הדסים משולשים, ערבות טריות ואתרוג נקי. המחיר משתנה לפי דרגת ההידור והזמינות סמוך לחג.',
      'לקבלת סט לפי בקשתכם — שלחו בקשת הצעת מחיר ונחזור אליכם עם האפשרויות.',
    ],
    materials: ['לולב', 'שלושה הדסים', 'שתי ערבות', 'אתרוג'],
    prepTimeDays: [1, 3], tags: ['סוכות', 'ארבעת המינים', 'מהדרין', 'הצעת מחיר'], relatedSlugs: ['etrog-box-silver-mehudar', 'honey-dish-apple-glass', 'rosh-hashana-plate-divided'],
    stockStatus: 'made-to-order', badges: ['recommended'], audience: ['men'], occasions: ['חג'],
  }),
  def({
    id: 'y12', sku: 'EB-HG-212', slug: 'rosh-hashana-plate-divided',
    titleHe: 'קערת ראש השנה מחולקת', imageUrl: `${IMG}/rosh-hashana-plate.svg`,
    category: 'חגים ומועדים', subcategory: 'ראש השנה',
    material: 'קרמיקה מעוצבת עם עיטור זהב', basePrice: 260, isCustomizable: false, iconKey: 'textile',
    shortDescription: 'קערה מחולקת לסימני ראש השנה — רימון, תמר, תפוח בדבש ושאר הברכות, במקום אחד.',
    longDescription: ['קערת ראש השנה מחולקת לתאים, לסידור מסודר ומכובד של סימני החג — רימון, תמר, תפוח בדבש, סלק, כרתי וקרא. עיטור זהב עדין במרכז עם ברכת "שנה טובה".'],
    materials: ['קרמיקה', 'עיטור זהב'], dimensions: 'קוטר 30 ס"מ',
    prepTimeDays: [2, 5], careInstructions: 'שטיפה עדינה ביד.',
    tags: ['ראש השנה', 'סימנים', 'שולחן החג'], relatedSlugs: ['honey-dish-apple-glass', 'arba-minim-set-mehadrin', 'seder-plate-silver-six'],
    stockStatus: 'in-stock', badges: ['recommended'], audience: ['family'], occasions: ['חג'],
  }),
  def({
    id: 'y13', sku: 'EB-HG-213', slug: 'mishloach-manot-tray-designed',
    titleHe: 'מגש משלוח מנות מעוצב', imageUrl: `${IMG}/mishloach-manot-tray.svg`,
    category: 'חגים ומועדים', subcategory: 'פורים',
    material: 'סלסלה עם ידית זהב', basePrice: 89, isCustomizable: false, iconKey: 'textile',
    shortDescription: 'סלסלת משלוח מנות מהודרת עם ידית — מוכנה למילוי ולהרשמה, מתנה שנעים לתת.',
    longDescription: ['סלסלת משלוח מנות מעוצבת עם ידית מוזהבת, מוכנה למילוי בפירות, ממתקים ויין. מראה חגיגי ומכובד שהופך את המשלוח למתנה של ממש. מגיעה ריקה למילוי אישי.'],
    materials: ['נצרים מעוצבים', 'ידית מוזהבת'], dimensions: '28×20 ס"מ',
    prepTimeDays: [1, 3], tags: ['פורים', 'משלוח מנות', 'מעוצב'], relatedSlugs: ['purim-crown-kids-costume', 'megillat-esther-klaf-case', 'gift-hostess-shabbat'],
    stockStatus: 'in-stock', badges: ['new'], audience: ['family'], occasions: ['חג'],
  }),
  def({
    id: 'y14', sku: 'EB-HG-214', slug: 'purim-crown-kids-costume',
    titleHe: 'כתר פורים לילדים', imageUrl: `${IMG}/purim-crown-kids.svg`,
    category: 'חגים ומועדים', subcategory: 'פורים',
    material: 'קרטון מוזהב עם אבנים', basePrice: 25, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'כתר מלכה אסתר נוצץ — משלים כל תחפושת פורים בגובה העיניים של הילדים.',
    longDescription: ['כתר פורים מוזהב עם אבני נוי צבעוניות, קל ונוח לראש הילד. משלים תחפושת של מלכה אסתר או המלך אחשוורוש ומוסיף המון שמחה לחג.'],
    materials: ['קרטון מצופה', 'אבני אקריל'], dimensions: 'היקף מתכוונן',
    prepTimeDays: [1, 2], tags: ['פורים', 'ילדים', 'תחפושת'], relatedSlugs: ['mishloach-manot-tray-designed', 'alephbet-wooden-puzzle', 'tzedakah-box-kids-color'],
    stockStatus: 'in-stock', badges: [], audience: ['kids'], occasions: ['חג'],
  }),
  def({
    id: 'y15', sku: 'EB-HG-215', slug: 'megillat-esther-klaf-case',
    titleHe: 'מגילת אסתר קלף בקופסה מהודרת', imageUrl: `${IMG}/megillat-esther-klaf.svg`,
    category: 'חגים ומועדים', subcategory: 'פורים',
    material: 'קלף עבודת סופר, קופסת עיטור', basePrice: 850, isCustomizable: false, iconKey: 'mezuzah', priceType: 'from',
    shortDescription: 'מגילת אסתר כשרה בכתב יד סופר, בתוך קופסת עיטור — לקריאה ולדורות.',
    longDescription: [
      'מגילת אסתר כתובה ביד על ידי סופר סת"ם מוסמך, על קלף מעובד, בתוך קופסת עיטור מהודרת. המחיר משתנה לפי גודל הכתב, ההידור והעיטור.',
      'המגילות עוברות הגהה. לפרטים ולבחירת רמת ההידור — שלחו בקשת הצעת מחיר.',
    ],
    materials: ['קלף עבודת סופר סת"ם', 'קופסה מעוטרת'], dimensions: 'גדלים שונים',
    prepTimeDays: [7, 21], tags: ['פורים', 'מגילה', 'סת"ם', 'הצעת מחיר'], relatedSlugs: ['mishloach-manot-tray-designed', 'megillat-esther-klaf-case', 'tefillin-beit-yosef-mehudarot'],
    stockStatus: 'made-to-order', badges: ['luxury'], audience: ['men'], occasions: ['חג'],
  }),

  // ================= מוצרים לילדים =================
  def({
    id: 'y16', sku: 'EB-KD-216', slug: 'siddur-kids-illustrated-first',
    titleHe: 'הסידור הראשון שלי — מאויר', imageUrl: `${IMG}/siddur-kids-illustrated.svg`,
    category: 'מוצרים לילדים', subcategory: 'ספרים לילדים',
    material: 'כריכה קשה, איורים צבעוניים', basePrice: 35, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'סידור ראשון לילדים — תפילות היום ביום עם איורים חמים ואותיות גדולות.',
    longDescription: ['סידור מאויר לילדים המכיר להם את תפילות היום־יום: מודה אני, ברכות, שמע וברכת המזון. אותיות גדולות, ניקוד מלא ואיורים חמים שמלווים כל תפילה.'],
    materials: ['כריכה קשה', 'הדפסת צבע'], dimensions: '17×20 ס"מ',
    prepTimeDays: [1, 2], tags: ['ילדים', 'סידור', 'חינוך'], relatedSlugs: ['brachot-book-kids-mah-mevarchim', 'netla-kids-colorful', 'shabbat-set-kids-starter'],
    stockStatus: 'in-stock', badges: ['bestseller'], audience: ['kids'], occasions: ['בר מצווה'],
  }),
  def({
    id: 'y17', sku: 'EB-KD-217', slug: 'brachot-book-kids-mah-mevarchim',
    titleHe: 'ספר "מה מברכים?" לילדים', imageUrl: `${IMG}/brachot-book-kids.svg`,
    category: 'מוצרים לילדים', subcategory: 'ספרים לילדים',
    material: 'כריכה קשה, איורים צבעוניים', basePrice: 39, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'ספר ברכות מאויר שמלמד ילדים איזו ברכה מברכים על כל מאכל — בכיף ובצבע.',
    longDescription: ['ספר מאויר שמלמד ילדים את ברכות הנהנין: על איזה מאכל מברכים "העץ", "האדמה", "שהכל" ועוד. איורים גדולים וברורים שהופכים את הלימוד למשחק.'],
    materials: ['כריכה קשה', 'הדפסת צבע'], dimensions: '20×20 ס"מ',
    prepTimeDays: [1, 2], tags: ['ילדים', 'ברכות', 'חינוך'], relatedSlugs: ['siddur-kids-illustrated-first', 'alephbet-wooden-puzzle', 'tzedakah-box-kids-color'],
    stockStatus: 'in-stock', badges: ['recommended'], audience: ['kids'],
  }),
  def({
    id: 'y18', sku: 'EB-KD-218', slug: 'netla-kids-colorful',
    titleHe: 'נטלת ילדים צבעונית', imageUrl: `${IMG}/netla-kids-color.svg`,
    category: 'מוצרים לילדים', subcategory: 'כלים לילדים',
    material: 'פלסטיק קשיח, בטוח לילדים', basePrice: 29, isCustomizable: false, iconKey: 'kiddush',
    shortDescription: 'נטלה קלה וצבעונית בגובה של הילדים — כדי שנטילת ידיים בבוקר תהיה כיף.',
    longDescription: ['נטלת ילדים קלת משקל מפלסטיק קשיח בטוח, עם שתי ידיות נוחות בגובה הילדים. צבעים עליזים שהופכים את נטילת הידיים בבוקר ולפני האוכל להרגל אהוב.'],
    materials: ['פלסטיק קשיח נטול BPA'], dimensions: 'גובה 13 ס"מ',
    prepTimeDays: [1, 2], tags: ['ילדים', 'נטילת ידיים', 'צבעוני'], relatedSlugs: ['siddur-kids-illustrated-first', 'shabbat-set-kids-starter', 'tzedakah-box-kids-color'],
    stockStatus: 'in-stock', badges: [], audience: ['kids'],
  }),
  def({
    id: 'y19', sku: 'EB-KD-219', slug: 'shabbat-set-kids-starter',
    titleHe: 'מארז שבת לילדים', imageUrl: `${IMG}/shabbat-set-kids.svg`,
    category: 'מוצרים לילדים', subcategory: 'מארזים',
    material: 'פמוטים, גביע וחלה מפלסטיק', basePrice: 69, isCustomizable: false, iconKey: 'candles',
    shortDescription: 'מארז שבת קטן ובטוח — פמוטים, גביע וכיסוי חלה, כדי שגם הילדים יערכו שולחן.',
    longDescription: ['מארז שבת לילדים הכולל זוג פמוטים קטנים, גביע קידוש וכיסוי חלה — הכל מחומרים בטוחים וקלים. מזמין את הילדים להשתתף בהכנת שולחן השבת ולחוש חלק מהמסורת.'],
    materials: ['פלסטיק בטוח', 'בד רך'], dimensions: 'מארז 24×18 ס"מ',
    prepTimeDays: [1, 3], tags: ['ילדים', 'שבת', 'מארז', 'חינוך'], relatedSlugs: ['netla-kids-colorful', 'siddur-kids-illustrated-first', 'candlestick-girl-first'],
    stockStatus: 'in-stock', badges: ['new'], audience: ['kids', 'family'], occasions: ['שבת'],
  }),
  def({
    id: 'y20', sku: 'EB-KD-220', slug: 'alephbet-wooden-puzzle',
    titleHe: 'פאזל אותיות עברי מעץ', imageUrl: `${IMG}/alephbet-puzzle.svg`,
    category: 'מוצרים לילדים', subcategory: 'משחקים',
    material: 'עץ מלא, צבעים בטוחים', basePrice: 45, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'פאזל עץ צבעוני של אותיות האלף-בית — הדרך המשחקית להכיר את האותיות.',
    longDescription: ['פאזל עץ מלא עם אותיות האלף-בית העברי בצבעים עליזים. הילדים לומדים את צורת האותיות ואת סדר האלף-בית תוך כדי משחק והרכבה. פינות מעוגלות וצבעים בטוחים.'],
    materials: ['עץ מלא', 'צבע על בסיס מים'], dimensions: '30×30 ס"מ',
    prepTimeDays: [1, 3], tags: ['ילדים', 'אלף-בית', 'משחק', 'עץ'], relatedSlugs: ['brachot-book-kids-mah-mevarchim', 'dreidels-wood-family-set', 'tzedakah-box-kids-color'],
    stockStatus: 'in-stock', badges: ['recommended'], audience: ['kids'],
  }),
  def({
    id: 'y21', sku: 'EB-KD-221', slug: 'tzedakah-box-kids-color',
    titleHe: 'קופת צדקה לילדים', imageUrl: `${IMG}/tzedakah-box-kids.svg`,
    category: 'מוצרים לילדים', subcategory: 'כלים לילדים',
    material: 'מתכת צבועה', basePrice: 32, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'קופת צדקה עליזה בגובה הילדים — כדי שמצוות הצדקה תתחיל כבר בגיל צעיר.',
    longDescription: ['קופת צדקה צבעונית מתכת עם חריץ למטבעות, בגובה ובעיצוב שמדברים לילדים. מרגילה את הילד לתת צדקה לפני שבת ולאורך השבוע. ניתן להוסיף את שם הילד.'],
    materials: ['מתכת צבועה'], dimensions: 'גובה 14 ס"מ',
    prepTimeDays: [1, 3], tags: ['ילדים', 'צדקה', 'חינוך'], relatedSlugs: ['tzedakah-box-shul-brass', 'shabbat-set-kids-starter', 'siddur-kids-illustrated-first'],
    stockStatus: 'in-stock', badges: [], audience: ['kids'],
    customization: { ...PRINT_PERSONAL, maxChars: 14, surcharges: { text: 8, symbol: 0, logo: 0, giftWrap: 10 } },
  }),

  // ================= בית כנסת ומוסדות =================
  def({
    id: 'y22', sku: 'EB-SG-222', slug: 'parochet-embroidered-custom',
    titleHe: 'פרוכת רקומה לארון קודש', imageUrl: `${IMG}/parochet-embroidered.svg`,
    category: 'בית כנסת ומוסדות', subcategory: 'ארון קודש',
    material: 'קטיפה עם רקמת חוט זהב', basePrice: 2800, isCustomizable: true, iconKey: 'textile', priceType: 'quote',
    shortDescription: 'פרוכת קטיפה רקומה בעבודת יד — לבתי כנסת, בהתאמה מלאה של צבע, כיתוב והקדשה.',
    longDescription: [
      'פרוכת לארון הקודש מקטיפה משובחת עם רקמת חוט זהב בעבודת יד: כתר תורה, מגן דוד, פסוקים והקדשה. מיוצרת במידה מדויקת של ארון הקודש שלכם.',
      'כל פרוכת מיוצרת בהזמנה מיוחדת. שלחו בקשת הצעת מחיר עם מידות, נוסח ההקדשה והצבע המבוקש.',
    ],
    materials: ['קטיפה', 'רקמת חוט זהב', 'בטנה מלאה'], dimensions: 'לפי מידת הארון',
    prepTimeDays: [21, 45], tags: ['בית כנסת', 'פרוכת', 'רקמה', 'הצעת מחיר', 'הקדשה'], relatedSlugs: ['torah-mantle-royal-blue', 'torah-crown-silver-royal', 'memorial-plaque-illuminated'],
    stockStatus: 'made-to-order', badges: ['handmade', 'exclusive'], audience: ['family'], occasions: ['בית חדש'],
  }),
  def({
    id: 'y23', sku: 'EB-SG-223', slug: 'torah-mantle-royal-blue',
    titleHe: 'מעיל לספר תורה — קטיפה מלכותית', imageUrl: `${IMG}/torah-mantle-royal.svg`,
    category: 'בית כנסת ומוסדות', subcategory: 'ספר תורה',
    material: 'קטיפה עם רקמת זהב', basePrice: 1400, isCustomizable: true, iconKey: 'textile', priceType: 'quote',
    shortDescription: 'מעיל ספר תורה רקום בהתאמה אישית — כתר, מגן דוד והקדשה, במידה מדויקת.',
    longDescription: [
      'מעיל לספר תורה מקטיפה מלכותית עם רקמת חוט זהב: כתר תורה, מגן דוד והקדשה. תפור במידה מדויקת של ספר התורה שלכם, עם פתחי עצי חיים מחוזקים.',
      'מיוצר בהזמנה. לפרטים, מידות ונוסח ההקדשה — שלחו בקשת הצעת מחיר.',
    ],
    materials: ['קטיפה', 'רקמת חוט זהב'], dimensions: 'לפי מידת הספר',
    prepTimeDays: [14, 30], tags: ['בית כנסת', 'ספר תורה', 'מעיל', 'רקמה', 'הצעת מחיר'], relatedSlugs: ['parochet-embroidered-custom', 'yad-torah-silver-pointer', 'torah-crown-silver-royal'],
    stockStatus: 'made-to-order', badges: ['handmade'], audience: ['family'],
  }),
  def({
    id: 'y24', sku: 'EB-SG-224', slug: 'yad-torah-silver-pointer',
    titleHe: 'יד לספר תורה מכסף', imageUrl: `${IMG}/yad-torah-silver.svg`,
    category: 'בית כנסת ומוסדות', subcategory: 'ספר תורה',
    material: 'כסף 925 בעבודת יד', basePrice: 890, isCustomizable: true, iconKey: 'gift', priceType: 'from',
    shortDescription: 'יד (מורה) לקריאת התורה מכסף טהור — עבודת אומן עם אצבע מחוטבת ושרשרת.',
    longDescription: [
      'יד לספר תורה מכסף 925 בעבודת יד: גוף מחוטב, אצבע מורה מדויקת ושרשרת נשיאה. פריט הקדשה מבוקש לבתי כנסת. המחיר משתנה לפי משקל ועיטור.',
      'ניתן לחרוט לוחית הקדשה. לרמות עיטור נוספות — שלחו בקשת הצעת מחיר.',
    ],
    materials: ['כסף סטרלינג 925'], dimensions: 'אורך 24 ס"מ',
    prepTimeDays: [7, 14], careInstructions: 'לנקות במטלית כסף.',
    tags: ['בית כנסת', 'ספר תורה', 'יד', 'כסף 925', 'הקדשה'], relatedSlugs: ['torah-crown-silver-royal', 'torah-mantle-royal-blue', 'torah-rimonim-silver-bells'],
    stockStatus: 'made-to-order', badges: ['handmade'], audience: ['men'],
    customization: { ...ENGRAVING_SILVER, positions: [{ id: 'plate', label: 'לוחית הקדשה' }] },
  }),
  def({
    id: 'y25', sku: 'EB-SG-225', slug: 'torah-crown-silver-royal',
    titleHe: 'כתר תורה מכסף', imageUrl: `${IMG}/torah-crown-silver.svg`,
    category: 'בית כנסת ומוסדות', subcategory: 'ספר תורה',
    material: 'כסף 925, אבני נוי', basePrice: 4800, isCustomizable: false, iconKey: 'gift', priceType: 'quote',
    shortDescription: 'כתר תורה מכסף בעבודת אומן — פריט מרכזי ומכובד לספר תורה בבית הכנסת.',
    longDescription: [
      'כתר תורה מכסף 925 בעבודת אומן: קשתות מעוטרות, אבני נוי צבעוניות ופעמונים. פריט הידור מרכזי לספר תורה, מתנת הקדשה מכובדת לבית כנסת או לישיבה.',
      'כל כתר מיוצר בהזמנה. שלחו בקשת הצעת מחיר לפרטים ולנוסח ההקדשה.',
    ],
    materials: ['כסף סטרלינג 925', 'אבני נוי'], dimensions: 'לפי מידת הספר',
    prepTimeDays: [21, 45], tags: ['בית כנסת', 'כתר תורה', 'כסף 925', 'הצעת מחיר', 'הידור'], relatedSlugs: ['yad-torah-silver-pointer', 'torah-rimonim-silver-bells', 'parochet-embroidered-custom'],
    stockStatus: 'made-to-order', badges: ['luxury', 'exclusive'], audience: ['family'],
  }),
  def({
    id: 'y26', sku: 'EB-SG-226', slug: 'ner-neshama-electric-memorial',
    titleHe: 'נר נשמה חשמלי לזיכרון', imageUrl: `${IMG}/ner-neshama-memorial.svg`,
    category: 'בית כנסת ומוסדות', subcategory: 'הנצחה',
    material: 'בסיס כסף, נורת LED', basePrice: 45, isCustomizable: false, iconKey: 'candles',
    shortDescription: 'נר נשמה חשמלי בטוח — דולק ברציפות לזיכרון, בלי אש ובלי חשש.',
    longDescription: ['נר נשמה חשמלי עם נורת LED בגוון להבה חמה ובסיס בגימור כסף. פתרון בטוח ונקי להדלקת נר לזיכרון או ביום השנה, ללא אש גלויה — מתאים לבית ולבית הכנסת.'],
    materials: ['בסיס מתכת', 'נורת LED', 'סוללות'], dimensions: 'גובה 12 ס"מ',
    prepTimeDays: [1, 2], tags: ['הנצחה', 'נר נשמה', 'יום השנה', 'בטיחות'], relatedSlugs: ['memorial-plaque-illuminated', 'tzedakah-box-shul-brass', 'havdalah-set-silver'],
    stockStatus: 'in-stock', badges: ['recommended'], audience: ['family'],
  }),
  def({
    id: 'y27', sku: 'EB-SG-227', slug: 'memorial-plaque-illuminated',
    titleHe: 'לוח הנצחה מואר', imageUrl: `${IMG}/memorial-plaque.svg`,
    category: 'בית כנסת ומוסדות', subcategory: 'הנצחה',
    material: 'לוח מתכת עם תאורה', basePrice: 1200, isCustomizable: true, iconKey: 'mezuzah', priceType: 'quote',
    shortDescription: 'לוח הנצחה עם שמות ותאריכי פטירה ותאורת נר לצד כל שם — לבית הכנסת.',
    longDescription: [
      'לוח הנצחה (יזכור) לבית הכנסת: מסגרת מתכת מהודרת, שמות ותאריכי פטירה, ונורית זיכרון לצד כל שם שנדלקת ביום השנה. מיוצר לפי מספר השמות והמידות הנדרשות.',
      'שלחו בקשת הצעת מחיר עם מספר השמות והמידות ונחזור אליכם.',
    ],
    materials: ['לוח מתכת', 'תאורת LED', 'לוחיות שם'], dimensions: 'לפי הזמנה',
    prepTimeDays: [21, 45], tags: ['בית כנסת', 'הנצחה', 'יזכור', 'הצעת מחיר'], relatedSlugs: ['ner-neshama-electric-memorial', 'tzedakah-box-shul-brass', 'parochet-embroidered-custom'],
    stockStatus: 'made-to-order', badges: ['exclusive'], audience: ['family'],
    customization: { ...PRINT_PERSONAL, positions: [{ id: 'plate', label: 'לוחיות השמות' }] },
  }),
  def({
    id: 'y28', sku: 'EB-SG-228', slug: 'tzedakah-box-shul-brass',
    titleHe: 'קופת צדקה לבית כנסת', imageUrl: `${IMG}/tzedakah-box-shul.svg`,
    category: 'בית כנסת ומוסדות', subcategory: 'כלי בית כנסת',
    material: 'פליז בגימור מוברש', basePrice: 180, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'קופת צדקה יציבה בגימור פליז — עם מנעול, לבית הכנסת ולמוסד.',
    longDescription: ['קופת צדקה בגימור פליז מוברש, עם חריץ מטבעות, דלת נעילה ובסיס יציב. מתאימה לבית הכנסת, לישיבה או לארגון. ניתן לחרוט את שם הקהילה או ייעוד הצדקה.'],
    materials: ['פליז מוברש', 'מנעול'], dimensions: 'גובה 18 ס"מ',
    prepTimeDays: [3, 7], tags: ['בית כנסת', 'צדקה', 'פליז', 'חריטה'], relatedSlugs: ['tzedakah-box-kids-color', 'ner-neshama-electric-memorial', 'memorial-plaque-illuminated'],
    stockStatus: 'in-stock', badges: [], audience: ['family'],
    customization: { ...ENGRAVING_SILVER, maxChars: 20, colors: [{ id: 'engraved', label: 'חריטה', hex: '#8A6E2E' }] },
  }),

  // ================= תוספות: הבדלה ותכשיטים =================
  def({
    id: 'y29', sku: 'EB-HM-229', slug: 'besamim-tower-silver',
    titleHe: 'מגדל בשמים מכסף', imageUrl: `${IMG}/besamim-tower-silver.svg`,
    category: 'תשמישי קדושה לבית', subcategory: 'הבדלה',
    material: 'כסף 925 בעבודת פילגרין', basePrice: 145, isCustomizable: true, iconKey: 'kiddush',
    shortDescription: 'מגדל בשמים מכסף בעיצוב חלונות מסורתי עם דגלון — לרגע ההבדלה.',
    longDescription: ['מגדל בשמים מכסף 925 בעיצוב מגדל מסורתי עם חלונות מחוררים, דגלון מסתובב ופעמון קטן. מחזיק את בשמי ההבדלה ומפיץ ריח נעים. ניתן לחרוט הקדשה על הבסיס.'],
    materials: ['כסף סטרלינג 925'], dimensions: 'גובה 17 ס"מ',
    prepTimeDays: [3, 7], careInstructions: 'לנקות במטלית כסף.',
    tags: ['הבדלה', 'בשמים', 'כסף 925', 'חריטה'], relatedSlugs: ['havdalah-set-silver', 'besamim-pomegranate-silver', 'kiddush-cup-jerusalem-925'],
    stockStatus: 'in-stock', badges: ['handmade'], audience: ['family'], occasions: ['שבת'],
    customization: { ...ENGRAVING_SILVER, maxChars: 16 },
  }),
  def({
    id: 'y30', sku: 'EB-HM-230', slug: 'besamim-pomegranate-silver',
    titleHe: 'הדס בשמים בצורת רימון', imageUrl: `${IMG}/besamim-pomegranate.svg`,
    category: 'תשמישי קדושה לבית', subcategory: 'הבדלה',
    material: 'כסף 925 עם אמייל', basePrice: 120, isCustomizable: false, iconKey: 'kiddush',
    shortDescription: 'קופסת בשמים בצורת רימון — סמל המצוות, עם מכסה כתר נפתח.',
    longDescription: ['קופסת בשמים בצורת רימון — סמל התורה והמצוות — מכסף 925 עם גימור אמייל אדום עמוק ומכסה כתר נפתח. מוסיפה יופי וסמליות לרגע ההבדלה.'],
    materials: ['כסף סטרלינג 925', 'אמייל'], dimensions: 'גובה 12 ס"מ',
    prepTimeDays: [2, 5], careInstructions: 'לנקות במטלית רכה בלבד.',
    tags: ['הבדלה', 'בשמים', 'רימון', 'כסף'], relatedSlugs: ['besamim-tower-silver', 'havdalah-set-silver', 'natla-silver-engraved'],
    stockStatus: 'in-stock', badges: ['handmade'], audience: ['family'], occasions: ['שבת'],
  }),
  def({
    id: 'y31', sku: 'EB-JW-231', slug: 'ring-shema-silver-band',
    titleHe: 'טבעת "שמע ישראל" מכסף', imageUrl: `${IMG}/ring-shema-silver.svg`,
    category: 'תכשיטי יודאיקה', subcategory: 'טבעות',
    material: 'כסף 925 עם חריטה מסתובבת', basePrice: 220, isCustomizable: true, iconKey: 'gift',
    shortDescription: 'טבעת כסף עם הפסוק "שמע ישראל" חרוט מסביב — הגנה ואמונה שמלווים תמיד.',
    longDescription: ['טבעת מכסף 925 עם הפסוק "שמע ישראל ה\' אלוקינו ה\' אחד" חרוט לאורך היקף הטבעת. עיצוב נקי ואלגנטי לגברים ולנשים. ניתן להוסיף חריטת שם או תאריך בפנים.'],
    materials: ['כסף סטרלינג 925'], dimensions: 'מידות 6–12',
    prepTimeDays: [3, 7], careInstructions: 'להסיר במגע עם מים וסבון לשמירה על הברק.',
    tags: ['תכשיט', 'טבעת', 'שמע ישראל', 'חריטה'], relatedSlugs: ['necklace-chai-gold-14k', 'earrings-magen-david-gold', 'necklace-magen-david-silver'],
    stockStatus: 'in-stock', badges: ['bestseller'], audience: ['men', 'women'], occasions: ['בר מצווה'],
    variantGroups: [{ id: 'size', label: 'מידה', options: [
      { id: '6', label: '6', priceDelta: 0 }, { id: '8', label: '8', priceDelta: 0 }, { id: '10', label: '10', priceDelta: 0 }, { id: '12', label: '12', priceDelta: 0 },
    ]}],
    customization: { ...ENGRAVING_SILVER, maxChars: 12, positions: [{ id: 'inner', label: 'חריטה פנימית' }], surcharges: { text: 40, symbol: 0, logo: 0, giftWrap: 25 } },
  }),
  def({
    id: 'y32', sku: 'EB-JW-232', slug: 'earrings-magen-david-gold',
    titleHe: 'עגילי מגן דוד', imageUrl: `${IMG}/earrings-magen-david.svg`,
    category: 'תכשיטי יודאיקה', subcategory: 'עגילים',
    material: 'ציפוי זהב 14K', basePrice: 95, isCustomizable: false, iconKey: 'gift',
    shortDescription: 'זוג עגילי מגן דוד עדינים בציפוי זהב — סמל יהודי קלאסי לכל יום.',
    longDescription: ['זוג עגילים תלויים בצורת מגן דוד עדין, בציפוי זהב 14K על כסף. קלים למגע ומתאימים ללבוש יומיומי או לאירוע. מגיעים בקופסת מתנה.'],
    materials: ['כסף בציפוי זהב 14K'], dimensions: 'אורך 2.5 ס"מ',
    prepTimeDays: [2, 5], careInstructions: 'להרחיק מבישום ומים.',
    tags: ['תכשיט', 'עגילים', 'מגן דוד', 'מתנה לאישה'], relatedSlugs: ['ring-shema-silver-band', 'necklace-chai-gold-14k', 'pendant-jerusalem-gilded'],
    stockStatus: 'in-stock', badges: ['new'], audience: ['women'], occasions: ['יולדת', 'בר מצווה'],
  }),
];
